%% 828update Phase 2: reference Gate A and final continuous rereference.

run(fullfile(fileparts(mfilename('fullpath')),'init_828_runtime.m'));
gatePath = fullfile(cfg.qc_dir,sprintf( ...
    '%s_828update_%s_phase02_reference_gate.csv', ...
    cfg.subject,cfg.reference_tag));
outputPath = fullfile(cfg.continuous_dir,cfg.referenced_set);
logPath = fullfile(cfg.logs_dir,sprintf( ...
    '%s_828update_%s_phase02_pass.txt',cfg.subject,cfg.reference_tag));
if exist(outputPath,'file') == 2 && exist(logPath,'file') == 2 && ...
        exist(gatePath,'file') == 2
    fprintf('828update Phase 2 already complete: %s\n',outputPath);
    return
end
assert(exist(outputPath,'file') == 0 && exist(logPath,'file') == 0, ...
    'Partial final Phase 2 output exists; inspect before rerunning.');

EEG = pop_loadset('filename',cfg.imported_set,'filepath',cfg.input_dir);
EEG = eeg_checkset(EEG);
labels = string({EEG.chanlocs.labels})';

if exist(gatePath,'file') == 0
    phase1QC = fullfile(cfg.qc_dir,sprintf( ...
        '%s_828update_%s_phase01_channel_qc.csv', ...
        cfg.subject,cfg.reference_tag));
    assert(exist(phase1QC,'file') == 2,'Run Phase 1 before Phase 2.');
    CHANNEL_QC = readtable(phase1QC,'TextType','string');
    automaticChannels = double(CHANNEL_QC.Channel(logical( ...
        CHANNEL_QC.AutomaticBadChannelCandidate)));
    channels = unique([cfg.m1_channel cfg.m2_channel ...
        cfg.bad_channel_candidates(:)' automaticChannels(:)'],'stable');
    data = double(EEG.data(channels,:));
    reviewReason = repmat("candidate",numel(channels),1);
    reviewReason(ismember(channels,[cfg.m1_channel cfg.m2_channel])) = ...
        "mandatory_mastoid";
    GATE = table(channels(:),labels(channels),reviewReason, ...
        std(data,0,2),max(data,[],2)-min(data,[],2), ...
        max(abs(data-median(data,2)),[],2), ...
        mean(abs(diff(data,1,2)) < 1e-9,2), ...
        'VariableNames',{'Channel','Label','ReviewReason','SD_uV', ...
        'Range_uV','CenteredMaxAbs_uV','FlatFraction'});
    writetable(GATE,gatePath);
end

if ~cfg.reference_review_complete
    fprintf(['GUI GATE A: inspect M1/M2 and every candidate channel. ' ...
        'Enter cfg.bad_channels and reference decision, set ' ...
        'reference_review_complete=true, rerun the config and Phase 2.\n']);
    fprintf('Reference gate table: %s\n',gatePath);
    return
end

switch cfg.reference_mode
    case 'average_mastoid'
        referenceChannels = [cfg.m1_channel cfg.m2_channel];
    case 'm1'
        assert(strlength(string(cfg.reference_exception_reason)) > 0, ...
            'M1-only reference requires a documented M2 reason.');
        referenceChannels = cfg.m1_channel;
    case 'm2'
        assert(strlength(string(cfg.reference_exception_reason)) > 0, ...
            'M2-only reference requires a documented M1 reason.');
        referenceChannels = cfg.m2_channel;
end
dimensionsBefore = size(EEG.data);
eventsBefore = EEG.event;
auxBefore = EEG.data(cfg.aux_channels,:);
EEG = pop_reref(EEG,referenceChannels,'exclude',cfg.aux_channels, ...
    'keepref','on','refica','remove');
EEG = eeg_checkset(EEG);
assert(isequal(size(EEG.data),dimensionsBefore));
assert(isequal({EEG.chanlocs.labels},cellstr(labels)'));
assert(isequaln(EEG.event,eventsBefore));
assert(max(abs(double(EEG.data(cfg.aux_channels,:))- ...
    double(auxBefore)),[],'all') == 0);
if strcmp(cfg.reference_mode,'average_mastoid')
    residual = mean(double(EEG.data(referenceChannels,:)),1);
else
    residual = double(EEG.data(referenceChannels,:));
end
assert(max(abs(residual),[],'all') < 1e-4, ...
    'Reference residual exceeds tolerance.');
EEG.etc.update828_reference = struct( ...
    'mode',cfg.reference_mode,'channels',referenceChannels, ...
    'bad_channels_recorded',cfg.bad_channels, ...
    'exception_reason',cfg.reference_exception_reason, ...
    'review_complete',true,'applied_before_filter_and_ica',true);
EEG.setname = erase(cfg.referenced_set,'.set');
n400u_assert_dataset_absent(outputPath);
EEG = pop_saveset(EEG,'filename',cfg.referenced_set, ...
    'filepath',cfg.continuous_dir);
CHECK = pop_loadset('filename',cfg.referenced_set, ...
    'filepath',cfg.continuous_dir);
assert(isequaln(CHECK.data,EEG.data));
assert(isequaln(CHECK.event,EEG.event));
n400u_write_stage_log(cfg,'phase02',{ ...
    sprintf('Reference mode: %s',cfg.reference_mode), ...
    sprintf('Reference channels: %s',mat2str(referenceChannels)), ...
    sprintf('Bad scalp channels recorded: %s',mat2str(cfg.bad_channels)), ...
    sprintf('Exception reason: %s',cfg.reference_exception_reason), ...
    sprintf('Maximum reference residual: %.12g',max(abs(residual),[],'all')), ...
    sprintf('Output: %s',outputPath)});
fprintf('828update Phase 2 PASS: reference=%s; saved %s.\n', ...
    cfg.reference_mode,outputPath);
