%% Validate the locked 828update configuration without modifying cfg.

required = {'subject','project_root','repo_root','eeglab_root', ...
    'input_dir','behavior_dir','result_root','continuous_dir','ica_dir', ...
    'epochs_dir','eventlists_dir','tables_dir','erp_dir','qc_dir', ...
    'logs_dir','bdf','eeg_channels','eog_channels','trigger_channel', ...
    'm1_channel','m2_channel','aux_channels','bad_channels', ...
    'reference_mode','reference_exception_reason', ...
    'reference_review_complete','analysis_rate','analysis_highpass', ...
    'line_notch_hz','analysis_lowpass','ica_rate','ica_highpass', ...
    'ica_channels', ...
    'run_ica','ica_review_complete','removed_ics', ...
    'epoch_ms','baseline_ms','artifact_bad_epochs', ...
    'artifact_review_complete','artifact_flag_bit','behavior_flag_bit'};
for k = 1:numel(required)
    assert(isfield(cfg,required{k}), ...
        'Missing 828update config field: %s',required{k});
end
assert(~contains(cfg.project_root,'TODO_') && ...
    ~contains(cfg.eeglab_root,'TODO_'), ...
    'Replace TODO paths in the participant config before running.');
assert(contains(cfg.result_root,[filesep 'result_update' filesep]), ...
    'result_root must be N400_project/result_update/<ID>.');
assert(~contains(cfg.result_root,[filesep 'derivatives' filesep]));
assert(~contains(cfg.result_root,[filesep 'no-ica' filesep]));
assert(isequal(cfg.eeg_channels,1:64));
assert(isequal(cfg.eog_channels,65:66));
assert(cfg.trigger_channel == 67);
assert(isequal(cfg.aux_channels,65:67));
assert(cfg.analysis_rate == 250);
assert(cfg.analysis_highpass == 0.1);
assert(cfg.analysis_highpass_order == 2);
assert(cfg.line_notch_hz == 50);
assert(cfg.analysis_lowpass == 30);
assert(cfg.analysis_lowpass_order == 8);
assert(cfg.ica_rate == 100 && cfg.ica_highpass == 1);
assert(isequal(cfg.ica_simple_threshold_uv,[-100 100]));
assert(isequal(cfg.epoch_ms,[-200 800]));
assert(isequal(cfg.baseline_ms,[-200 0]));
assert(cfg.artifact_flag_bit == 1 && cfg.behavior_flag_bit == 2);
assert(ismember(cfg.reference_mode,{'average_mastoid','m1','m2'}));
assert(all(cfg.bad_channels == fix(cfg.bad_channels)));
assert(all(ismember(cfg.bad_channels,cfg.eeg_channels)));
assert(isempty(intersect(cfg.bad_channels, ...
    [cfg.m1_channel cfg.m2_channel cfg.aux_channels])), ...
    'M1/M2/EOG/TRIGGER cannot be scalp bad channels.');
assert(all(ismember(cfg.ica_channels,cfg.eeg_channels)));
assert(isempty(intersect(cfg.ica_channels,cfg.bad_channels)));
if strcmp(cfg.reference_mode,'m1')
    assert(~ismember(cfg.m1_channel,cfg.ica_channels));
elseif strcmp(cfg.reference_mode,'m2')
    assert(~ismember(cfg.m2_channel,cfg.ica_channels));
end
