%% 905 Phase 3: 0.1-Hz HP -> 50-Hz PMnotch -> 30-Hz LP at 250 Hz.

run(fullfile(fileparts(mfilename('fullpath')),'init_905_runtime.m'));
outputPath = fullfile(cfg.continuous_dir,cfg.preica_set);
qcPath = fullfile(cfg.qc_dir,sprintf( ...
    '%s_905_%s_phase03_filter_qc.csv',cfg.subject,cfg.reference_tag));
logPath = fullfile(cfg.logs_dir,sprintf( ...
    '%s_905_%s_phase03_pass.txt',cfg.subject,cfg.reference_tag));
present = [exist(outputPath,'file') == 2,exist(qcPath,'file') == 2, ...
    exist(logPath,'file') == 2];
if all(present)
    fprintf('905 Phase 3 already complete: %s\n',outputPath);
    return
end
assert(~any(present),'Partial Phase 3 output exists; inspect before rerunning.');

EEG = pop_loadset('filename',cfg.referenced_set,'filepath',cfg.continuous_dir);
EEG = eeg_checkset(EEG);
assert(EEG.nbchan == cfg.expected_analysis_channels);
labelsBefore = {EEG.chanlocs.labels};
assert(isempty(intersect(upper(string(labelsBefore)), ...
    upper(string(cfg.fixed_excluded_labels)))));
eogChannels = n400u_channel_indices(EEG,cfg.eog_labels);
triggerChannel = n400u_channel_indices(EEG,{cfg.trigger_label});
auxChannels = [eogChannels triggerChannel];
scalpChannels = setdiff(1:EEG.nbchan,auxChannels,'stable');
badChannels = n400u_channel_indices(EEG,cfg.bad_channel_labels);
goodScalp = setdiff(scalpChannels,badChannels,'stable');
filterChannels = [scalpChannels eogChannels];

eventCodesBefore = arrayfun(@(x) n400u_event_code(x.type),EEG.event);
targetCountBefore = sum(ismember(eventCodesBefore,[111:115 121:125]));
inputRate = EEG.srate;
preSD = std(double(EEG.data),0,2);
preRange = max(double(EEG.data),[],2)-min(double(EEG.data),[],2);

EEG = pop_resample(EEG,cfg.analysis_rate);
triggerChannel = n400u_channel_indices(EEG,{cfg.trigger_label});
triggerAfterResample = EEG.data(triggerChannel,:);
eventLatenciesAfterResample = double([EEG.event.latency]);
EEG = pop_basicfilter(EEG,filterChannels, ...
    'Filter','highpass','Design','butter', ...
    'Cutoff',cfg.analysis_highpass,'Order',cfg.analysis_highpass_order, ...
    'RemoveDC','on','Boundary','boundary');
% PMnotch requires Design='notch'; omitting it can silently pass data through.
EEG = pop_basicfilter(EEG,filterChannels, ...
    'Filter','PMnotch','Design','notch', ...
    'Cutoff',cfg.line_notch_hz,'RemoveDC','on','Boundary','boundary');
EEG = pop_basicfilter(EEG,filterChannels, ...
    'Filter','lowpass','Design','butter', ...
    'Cutoff',cfg.analysis_lowpass,'Order',cfg.analysis_lowpass_order, ...
    'RemoveDC','on','Boundary','boundary');
EEG = eeg_checkset(EEG);
assert(max(abs(double(EEG.data(triggerChannel,:))- ...
    double(triggerAfterResample)),[],'all') == 0, ...
    'TRIGGER changed during filtering.');
assert(isequal(double([EEG.event.latency]),eventLatenciesAfterResample));
assert(isequal({EEG.chanlocs.labels},labelsBefore));
assert(all(isfinite(double(EEG.data(:)))));
eventCodesAfter = arrayfun(@(x) n400u_event_code(x.type),EEG.event);
assert(sum(ismember(eventCodesAfter,[111:115 121:125])) == ...
    targetCountBefore && targetCountBefore == cfg.expected_trials);
residual = mean(double(EEG.data(goodScalp,:)),1);
% Preserve the strict CAR check while accounting for single-precision data.
carResidualTolerance = 5e-3;
assert(max(abs(residual),[],'all') < carResidualTolerance, ...
    'Initial CAR residual changed unexpectedly during filtering.');

postSD = std(double(EEG.data),0,2);
postRange = max(double(EEG.data),[],2)-min(double(EEG.data),[],2);
FILTER_QC = table((1:EEG.nbchan)',string({EEG.chanlocs.labels})', ...
    preSD,preRange,postSD,postRange, ...
    'VariableNames',{'Channel','Label','PreFilterSD_uV', ...
    'PreFilterRange_uV','PostFilterSD_uV','PostFilterRange_uV'});
writetable(FILTER_QC,qcPath);
EEG.setname = erase(cfg.preica_set,'.set');
EEG.etc.n400_905_filter = struct('source',cfg.referenced_set, ...
    'input_rate_hz',inputRate,'output_rate_hz',cfg.analysis_rate, ...
    'highpass_hz',cfg.analysis_highpass, ...
    'highpass_effective_order',cfg.analysis_highpass_order, ...
    'line_notch_hz',cfg.line_notch_hz, ...
    'line_notch_filter','ERPLAB PMnotch','line_notch_design','notch', ...
    'lowpass_hz',cfg.analysis_lowpass, ...
    'lowpass_effective_order',cfg.analysis_lowpass_order, ...
    'trigger_filtered',false);
n400u_assert_dataset_absent(outputPath);
EEG = pop_saveset(EEG,'filename',cfg.preica_set,'filepath',cfg.continuous_dir);
CHECK = pop_loadset('filename',cfg.preica_set,'filepath',cfg.continuous_dir);
assert(isequaln(CHECK.data,EEG.data));
n400u_write_stage_log(cfg,'phase03',{ ...
    sprintf('Input: %s',cfg.referenced_set), ...
    sprintf('Input rate: %g Hz',inputRate), ...
    sprintf('Output rate: %g Hz',cfg.analysis_rate), ...
    sprintf('Filter order: %g-Hz HP -> %g-Hz PMnotch -> %g-Hz LP', ...
        cfg.analysis_highpass,cfg.line_notch_hz,cfg.analysis_lowpass), ...
    'TRIGGER filtered: 0', ...
    sprintf('Initial CAR channel count: %d',numel(goodScalp)), ...
    sprintf('Target events: %d',targetCountBefore), ...
    sprintf('Output: %s',outputPath)});
fprintf(['905 Phase 3 PASS: %g-Hz HP -> %g-Hz PMnotch -> %g-Hz LP ' ...
    'at %g Hz; saved %s.\n'],cfg.analysis_highpass,cfg.line_notch_hz, ...
    cfg.analysis_lowpass,cfg.analysis_rate,outputPath);
