%% 905 Phase 2: Gate A, fixed channel removal, and initial scalp CAR.

run(fullfile(fileparts(mfilename('fullpath')),'init_905_runtime.m'));
gatePath = fullfile(cfg.qc_dir,sprintf( ...
    '%s_905_%s_phase02_reference_gate.csv',cfg.subject,cfg.reference_tag));
outputPath = fullfile(cfg.continuous_dir,cfg.referenced_set);
logPath = fullfile(cfg.logs_dir,sprintf( ...
    '%s_905_%s_phase02_pass.txt',cfg.subject,cfg.reference_tag));
if exist(outputPath,'file') == 2 && exist(logPath,'file') == 2 && ...
        exist(gatePath,'file') == 2
    fprintf('905 Phase 2 already complete: %s\n',outputPath);
    return
end
assert(exist(outputPath,'file') == 0 && exist(logPath,'file') == 0, ...
    'Partial final Phase 2 output exists; inspect before rerunning.');

EEG = pop_loadset('filename',cfg.imported_set,'filepath',cfg.input_dir);
EEG = eeg_checkset(EEG);
labels = strtrim(string({EEG.chanlocs.labels}))';
fixedChannels = n400u_channel_indices(EEG,cfg.fixed_excluded_labels);
eogChannels = n400u_channel_indices(EEG,cfg.eog_labels);
triggerChannel = n400u_channel_indices(EEG,{cfg.trigger_label});
auxChannels = [eogChannels triggerChannel];

if exist(gatePath,'file') == 0
    phase1QC = fullfile(cfg.qc_dir,sprintf( ...
        '%s_905_%s_phase01_channel_qc.csv',cfg.subject,cfg.reference_tag));
    assert(exist(phase1QC,'file') == 2,'Run Phase 1 before Phase 2.');
    CHANNEL_QC = readtable(phase1QC,'TextType','string');
    automaticChannels = double(CHANNEL_QC.RawChannel(logical( ...
        CHANNEL_QC.AutomaticBadChannelCandidate)))';
    configuredChannels = n400u_channel_indices( ...
        EEG,cfg.bad_channel_candidate_labels);
    comparisonChannels = n400u_channel_indices(EEG,{'FZ','CZ','CPZ','PZ'});
    reviewChannels = unique([configuredChannels automaticChannels ...
        comparisonChannels],'stable');
    reviewReason = repmat("normal_comparison",numel(reviewChannels),1);
    reviewReason(ismember(reviewChannels, ...
        unique([configuredChannels automaticChannels]))) = "bad_channel_candidate";
    data = double(EEG.data(reviewChannels,:));
    GATE = table(reviewChannels(:),labels(reviewChannels),reviewReason, ...
        std(data,0,2),max(data,[],2)-min(data,[],2), ...
        max(abs(data-median(data,2)),[],2), ...
        mean(abs(diff(data,1,2)) < 1e-9,2), ...
        'VariableNames',{'RawChannel','Label','ReviewReason','SD_uV', ...
        'Range_uV','CenteredMaxAbs_uV','FlatFraction'});
    writetable(GATE,gatePath);
end

if ~cfg.reference_review_complete
    fprintf(['GUI GATE A: inspect every candidate with normal comparison ' ...
        'channels. Enter cfg.bad_channel_labels using labels only, set ' ...
        'reference_review_complete=true, reload the config, and rerun.\n']);
    fprintf('Reference gate table: %s\n',gatePath);
    return
end

rawScalp = setdiff(1:EEG.nbchan,auxChannels,'stable');
badRawChannels = n400u_channel_indices(EEG,cfg.bad_channel_labels);
assert(all(ismember(badRawChannels,rawScalp)) && ...
    isempty(intersect(badRawChannels,fixedChannels)), ...
    'Ordinary bad channels must be retained scalp channels.');
eventsBefore = EEG.event;
auxBefore = EEG.data(auxChannels,:);
labelsExpected = cellstr(labels(setdiff(1:EEG.nbchan,fixedChannels,'stable')))';

EEG = pop_select(EEG,'nochannel',fixedChannels);
EEG = eeg_checkset(EEG);
assert(EEG.nbchan == cfg.expected_analysis_channels);
assert(isequal({EEG.chanlocs.labels},labelsExpected));
eogChannels = n400u_channel_indices(EEG,cfg.eog_labels);
triggerChannel = n400u_channel_indices(EEG,{cfg.trigger_label});
auxChannels = [eogChannels triggerChannel];
scalpChannels = setdiff(1:EEG.nbchan,auxChannels,'stable');
badChannels = n400u_channel_indices(EEG,cfg.bad_channel_labels);
goodScalp = setdiff(scalpChannels,badChannels,'stable');
assert(numel(scalpChannels) == cfg.expected_analysis_scalp_channels);
assert(numel(goodScalp) >= 2,'At least two good scalp channels are required.');
badBefore = EEG.data(badChannels,:);

EEG = pop_reref(EEG,[],'exclude',[auxChannels badChannels], ...
    'refica','remove');
EEG = eeg_checkset(EEG);
assert(isequaln(EEG.event,eventsBefore));
assert(max(abs(double(EEG.data(auxChannels,:))-double(auxBefore)),[],'all') == 0);
if ~isempty(badChannels)
    assert(max(abs(double(EEG.data(badChannels,:))-double(badBefore)), ...
        [],'all') == 0,'Excluded bad-channel samples changed during CAR.');
end
residual = mean(double(EEG.data(goodScalp,:)),1);
assert(max(abs(residual),[],'all') < 1e-3, ...
    'Initial CAR residual exceeds tolerance.');

EEG.etc.n400_905_reference = struct( ...
    'mode','common_average_good_scalp', ...
    'fixed_excluded_labels',{cellstr(string(cfg.fixed_excluded_labels))}, ...
    'bad_channel_labels',{cellstr(string(cfg.bad_channel_labels))}, ...
    'reference_labels',{cellstr(string({EEG.chanlocs(goodScalp).labels}))}, ...
    'auxiliary_labels',{cellstr([string(cfg.eog_labels) string(cfg.trigger_label)])}, ...
    'review_complete',true,'applied_before_filter_and_ica',true);
EEG.setname = erase(cfg.referenced_set,'.set');
n400u_assert_dataset_absent(outputPath);
EEG = pop_saveset(EEG,'filename',cfg.referenced_set, ...
    'filepath',cfg.continuous_dir);
CHECK = pop_loadset('filename',cfg.referenced_set, ...
    'filepath',cfg.continuous_dir);
assert(isequaln(CHECK.data,EEG.data));
assert(isequaln(CHECK.event,EEG.event));
n400u_write_stage_log(cfg,'phase02',{ ...
    'Reference mode: common average of good retained scalp channels', ...
    sprintf('Permanently removed: %s',strjoin(string(cfg.fixed_excluded_labels),',')), ...
    sprintf('Ordinary bad scalp channels excluded: %s', ...
        strjoin(string(cfg.bad_channel_labels),',')), ...
    sprintf('Initial CAR channel count: %d',numel(goodScalp)), ...
    sprintf('Maximum initial CAR residual: %.12g',max(abs(residual),[],'all')), ...
    sprintf('Output: %s',outputPath)});
fprintf(['905 Phase 2 PASS: removed M1/M2/CB1/CB2; initial CAR used ' ...
    '%d good scalp channels; saved %s.\n'],numel(goodScalp),outputPath);
