%% Validate the locked 905 configuration without modifying cfg.

required = {'subject','project_root','skill_root','eeglab_root', ...
    'input_dir','behavior_dir','result_root','continuous_dir','ica_dir', ...
    'epochs_dir','eventlists_dir','tables_dir','erp_dir','qc_dir', ...
    'logs_dir','bdf','fixed_excluded_labels','eog_labels', ...
    'trigger_label','bad_channel_candidate_labels','bad_channel_labels', ...
    'reference_mode','final_car_for_all', ...
    'reference_review_complete','analysis_rate','analysis_highpass', ...
    'analysis_highpass_order','line_notch_hz','analysis_lowpass', ...
    'analysis_lowpass_order','ica_rate','ica_highpass', ...
    'ica_highpass_order','ica_task_end_seconds', ...
    'ica_simple_threshold_uv','ica_random_seed', ...
    'run_ica','ica_review_complete','removed_ics', ...
    'epoch_ms','baseline_ms','artifact_bad_epochs', ...
    'artifact_review_complete','artifact_flag_bit','behavior_flag_bit', ...
    'expected_raw_channels','expected_raw_scalp_channels', ...
    'expected_analysis_scalp_channels','expected_analysis_channels', ...
    'expected_trials','expected_bins','expected_trials_per_bin'};
for k = 1:numel(required)
    assert(isfield(cfg,required{k}), ...
        'Missing 905 config field: %s',required{k});
end
assert(~contains(cfg.project_root,'TODO_') && ...
    ~contains(cfg.skill_root,'TODO_') && ...
    ~contains(cfg.eeglab_root,'TODO_'), ...
    'Replace TODO paths in the participant config before running.');
assert(exist(cfg.skill_root,'dir') == 7,'905 skill directory not found.');
assert(exist(cfg.bdf,'file') == 2,'Locked BDF file not found.');
assert(contains(cfg.result_root,[filesep 'result_update' filesep]), ...
    'result_root must be N400_project/result_update/<ID>.');
assert(~contains(cfg.result_root,[filesep 'derivatives' filesep]));
assert(~contains(cfg.result_root,[filesep 'no-ica' filesep]));
assert(contains(cfg.result_root,[filesep '905_car']));
assert(isequal(upper(string(cfg.fixed_excluded_labels)), ...
    ["M1" "M2" "CB1" "CB2"]));
assert(isequal(upper(string(cfg.eog_labels)),["VEOG" "HEOG"]));
assert(strcmpi(cfg.trigger_label,'TRIGGER'));
assert(cfg.analysis_rate == 250);
assert(cfg.analysis_highpass == 0.1);
assert(cfg.analysis_highpass_order == 2);
assert(cfg.line_notch_hz == 50);
assert(cfg.analysis_lowpass == 30);
assert(cfg.analysis_lowpass_order == 8);
assert(cfg.ica_rate == 100 && cfg.ica_highpass == 1);
assert(isequal(cfg.ica_simple_threshold_uv,[-100 100]));
assert(isequal(cfg.epoch_ms,[-200 800]));
assert(isequal(cfg.baseline_ms,[-200 0]));
assert(cfg.artifact_flag_bit == 1 && cfg.behavior_flag_bit == 2);
assert(strcmp(cfg.reference_mode,'common_average'));
assert(isequal(cfg.final_car_for_all,true));
assert(cfg.expected_raw_channels == 67);
assert(cfg.expected_raw_scalp_channels == 64);
assert(cfg.expected_analysis_scalp_channels == 60);
assert(cfg.expected_analysis_channels == 63);
assert(cfg.expected_trials == 300 && cfg.expected_bins == 10 && ...
    cfg.expected_trials_per_bin == 30);
assert(iscellstr(cfg.bad_channel_candidate_labels));
assert(iscellstr(cfg.bad_channel_labels));
reserved = upper([string(cfg.fixed_excluded_labels) ...
    string(cfg.eog_labels) string(cfg.trigger_label)]);
assert(isempty(intersect(upper(string(cfg.bad_channel_labels)),reserved)), ...
    'Fixed-excluded and auxiliary labels cannot be ordinary bad channels.');
assert(numel(unique(upper(string(cfg.bad_channel_labels)))) == ...
    numel(cfg.bad_channel_labels),'Duplicate bad-channel labels.');
