%% Phase 2: resample and apply the locked 0.1-30 Hz analysis filter.

run(fullfile(cfg.repo_root,'scripts','systematic', ...
    'init_n400_runtime.m'));
outputFile = fullfile(cfg.deriv_dir,cfg.preica_set);
assert(exist(outputFile,'file') == 0, ...
    'Phase 2 output exists; stopped without overwriting.');

EEG = pop_loadset('filename',cfg.imported_set, ...
    'filepath',cfg.input_dir);
EEG = pop_resample(EEG,cfg.analysis_rate);
EEG = pop_basicfilter(EEG, ...
    [cfg.eeg_channels cfg.eog_channels], ...
    'Filter','highpass', ...
    'Design','butter', ...
    'Cutoff',cfg.analysis_highpass, ...
    'Order',cfg.analysis_highpass_order, ...
    'RemoveDC','on', ...
    'Boundary','boundary');
EEG = pop_basicfilter(EEG, ...
    [cfg.eeg_channels cfg.eog_channels], ...
    'Filter','lowpass', ...
    'Design','butter', ...
    'Cutoff',cfg.analysis_lowpass, ...
    'Order',cfg.analysis_lowpass_order, ...
    'RemoveDC','off', ...
    'Boundary','boundary');
EEG.setname = erase(cfg.preica_set,'.set');

assert(EEG.srate == cfg.analysis_rate);
assert(all(isfinite(EEG.data(:))));
assert(numel(unique(string( ...
    {EEG.chanlocs.labels}))) == EEG.nbchan);

EEG = pop_saveset(EEG,'filename', ...
    cfg.preica_set,'filepath',cfg.deriv_dir);
CHECK = pop_loadset('filename', ...
    cfg.preica_set,'filepath',cfg.deriv_dir);
assert(isequal(size(CHECK.data),size(EEG.data)));
assert(CHECK.srate == cfg.analysis_rate);
assert(isequal({CHECK.chanlocs.labels}, ...
    {EEG.chanlocs.labels}));
fprintf(['Phase 2 PASS: %s; %g Hz; ' ...
    'analysis filter %g-%g Hz; saved %s.\n'], ...
    cfg.subject,EEG.srate, ...
    cfg.analysis_highpass,cfg.analysis_lowpass, ...
    outputFile);
