%% Phase 6: behavior ledger, primary/all-clean averages, save/reload ERP QC.

run(fullfile(cfg.repo_root,'scripts','systematic', ...
    'init_n400_runtime.m'));

if exist(cfg.tables_dir,'dir') ~= 7
    mkdir(cfg.tables_dir);
end
if exist(cfg.erp_dir,'dir') ~= 7
    mkdir(cfg.erp_dir);
end
ledgerPath = fullfile(cfg.tables_dir,cfg.ledger_csv);
primaryERPPath = fullfile(cfg.erp_dir,cfg.primary_erp);
sensitivityERPPath = fullfile( ...
    cfg.erp_dir,cfg.sensitivity_erp);
assert(exist(ledgerPath,'file') == 0 && ...
    exist(primaryERPPath,'file') == 0 && ...
    exist(sensitivityERPPath,'file') == 0, ...
    'Phase 6 output exists; stopped without overwriting.');

EEG = pop_loadset('filename',cfg.flagged_set, ...
    'filepath',cfg.deriv_dir);
assert(EEG.trials == cfg.expected_trials);

%% Behavior-to-EEG ledger

behaviorFile = fullfile( ...
    cfg.behavior_dir,[cfg.subject '.csv']);
raw = readcell(behaviorFile, ...
    'Delimiter',',','TextType','string');
headers = strip(localText(raw(1,:)));
cells = raw(2:end,:);
condition = upper(strip(localText( ...
    cells(:,localHeader(headers,'condition')))));
snr = lower(strip(localText( ...
    cells(:,localHeader(headers,'snr')))));
correct = localNumeric( ...
    cells(:,localHeader(headers,'Correct')));
assert(numel(correct) == cfg.expected_trials);
assert(all(ismember(correct,[0 1])));

expectedCode = nan(cfg.expected_trials,1);
expectedBin = nan(cfg.expected_trials,1);
for row = 1:cfg.expected_trials
    snrIndex = find(snr(row) == ...
        ["-4","-2","4","6","quiet"]);
    assert(isscalar(snrIndex));
    if condition(row) == "HC"
        expectedCode(row) = 110+snrIndex;
        expectedBin(row) = snrIndex;
    elseif condition(row) == "LC"
        expectedCode(row) = 120+snrIndex;
        expectedBin(row) = 5+snrIndex;
    else
        error('Unexpected condition at row %d.',row);
    end
end

eegCode = nan(cfg.expected_trials,1);
eegBin = nan(cfg.expected_trials,1);
artifact = false(cfg.expected_trials,1);
for ep = 1:cfg.expected_trials
    item = EEG.epoch(ep).eventitem;
    if iscell(item), item = item{1}; end
    info = EEG.EVENTLIST.eventinfo(item);
    eegCode(ep) = double(info.code);
    bins = info.bini;
    if iscell(bins), bins = cell2mat(bins); end
    bins = bins(bins >= 1 & ...
        bins <= cfg.expected_bins);
    assert(isscalar(bins));
    eegBin(ep) = bins;
    artifact(ep) = bitget( ...
        uint16(info.flag), ...
        cfg.artifact_flag_bit) == 1;
end
assert(isequal(eegCode,expectedCode));
assert(isequal(eegBin,expectedBin));

eegClean = ~artifact;
primaryGood = correct == 1 & eegClean;
LEDGER = table( ...
    repmat(string(cfg.subject), ...
    cfg.expected_trials,1), ...
    (1:cfg.expected_trials)', ...
    condition,snr,correct, ...
    expectedCode,eegCode,eegBin, ...
    artifact,eegClean,primaryGood, ...
    'VariableNames',{ ...
    'Participant','EEGEpoch','Condition','SNR', ...
    'Correct','ExpectedTargetCode','EEGTargetCode', ...
    'Bin','ArtifactFlagBit1','EEGClean', ...
    'PrimaryCorrectClean'});
writetable(LEDGER,ledgerPath);

%% Add behavior bit 2 and synchronize the total rejection mask.

PRIMARY = EEG;
incorrect = correct == 0;
PRIMARY.reject.rejbehavior = incorrect';
PRIMARY.reject.rejbehaviorE = ...
    false(PRIMARY.nbchan,PRIMARY.trials);
for ep = 1:PRIMARY.trials
    eventIndex = PRIMARY.epoch(ep).event;
    eventItem = PRIMARY.epoch(ep).eventitem;
    if iscell(eventIndex), eventIndex = eventIndex{1}; end
    if iscell(eventItem), eventItem = eventItem{1}; end
    assert(isscalar(eventIndex) && ...
        isscalar(eventItem), ...
        'Expected one time-locking event per epoch.');
    flag = bitset(uint16( ...
        PRIMARY.epoch(ep).eventflag), ...
        2,incorrect(ep));
    PRIMARY.epoch(ep).eventflag = double(flag);
    PRIMARY.event(eventIndex).flag = double(flag);
    PRIMARY.EVENTLIST.eventinfo(eventItem).flag = ...
        double(flag);
end
PRIMARY.reject.rejmanual = ...
    (artifact | incorrect)';

%% Average, save, reload, and verify.

ERP_PRIMARY = pop_averager(PRIMARY, ...
    'Criterion','good', ...
    'ExcludeBoundary','on', ...
    'SEM','on','Warning','off', ...
    'DQ_flag',1);
ERP_SENSITIVITY = pop_averager(EEG, ...
    'Criterion','good', ...
    'ExcludeBoundary','on', ...
    'SEM','on','Warning','off', ...
    'DQ_flag',1);
ERP_PRIMARY.erpname = sprintf( ...
    '%s_primary_correct_clean',cfg.subject);
ERP_SENSITIVITY.erpname = sprintf( ...
    '%s_sensitivity_all_clean',cfg.subject);
ERP_PRIMARY.subject = cfg.subject;
ERP_SENSITIVITY.subject = cfg.subject;

[ERP_PRIMARY,statusPrimary] = pop_savemyerp( ...
    ERP_PRIMARY,'erpname',ERP_PRIMARY.erpname, ...
    'filename',cfg.primary_erp, ...
    'filepath',cfg.erp_dir, ...
    'gui','none','Warning','off');
[ERP_SENSITIVITY,statusSensitivity] = ...
    pop_savemyerp(ERP_SENSITIVITY, ...
    'erpname',ERP_SENSITIVITY.erpname, ...
    'filename',cfg.sensitivity_erp, ...
    'filepath',cfg.erp_dir, ...
    'gui','none','Warning','off');
assert(statusPrimary == 2 && ...
    statusSensitivity == 2);

PRIMARY_CHECK = pop_loaderp( ...
    'filename',cfg.primary_erp, ...
    'filepath',cfg.erp_dir, ...
    'UpdateMainGui','off','History','off');
SENSITIVITY_CHECK = pop_loaderp( ...
    'filename',cfg.sensitivity_erp, ...
    'filepath',cfg.erp_dir, ...
    'UpdateMainGui','off','History','off');
assert(isequaln(PRIMARY_CHECK.bindata, ...
    ERP_PRIMARY.bindata));
assert(isequaln(SENSITIVITY_CHECK.bindata, ...
    ERP_SENSITIVITY.bindata));
assert(isequaln(PRIMARY_CHECK.binerror, ...
    ERP_PRIMARY.binerror));
assert(isequaln(SENSITIVITY_CHECK.binerror, ...
    ERP_SENSITIVITY.binerror));
assert(sum(PRIMARY_CHECK.ntrials.accepted) == ...
    sum(primaryGood));
assert(sum(SENSITIVITY_CHECK.ntrials.accepted) == ...
    sum(eegClean));

fprintf('Phase 6 PASS: primary accepted per bin = ');
fprintf('%d ',PRIMARY_CHECK.ntrials.accepted);
fprintf('\nSensitivity accepted per bin = ');
fprintf('%d ',SENSITIVITY_CHECK.ntrials.accepted);
fprintf('\nERP save/reload differences: 0.\n');

function index = localHeader(headers,name)
index = find(headers == string(name),1);
assert(~isempty(index),'Missing behavior column: %s',name);
end

function output = localText(input)
output = strings(numel(input),1);
for k = 1:numel(input)
    value = input{k};
    if isstring(value) || ischar(value)
        output(k) = string(value);
    elseif isnumeric(value) || islogical(value)
        output(k) = string(value);
    else
        output(k) = missing;
    end
end
end

function output = localNumeric(input)
output = nan(numel(input),1);
for k = 1:numel(input)
    value = input{k};
    if isnumeric(value) || islogical(value)
        output(k) = double(value);
    else
        output(k) = str2double(string(value));
    end
end
end
