%% Phase 4: final reference, EventList, BINLISTER, binned continuous SET.

run(fullfile(cfg.repo_root,'scripts','systematic', ...
    'init_n400_runtime.m'));

refPath = fullfile(cfg.deriv_dir,cfg.ref_set);
binnedPath = fullfile(cfg.deriv_dir,cfg.binned_set);
if exist(binnedPath,'file') == 2
    fprintf('Phase 4 already complete: %s\n',binnedPath);
    return
end
assert(exist(refPath,'file') == 0 && ...
    exist(binnedPath,'file') == 0, ...
    'Phase 4 output exists; stopped without overwriting.');

EEG = pop_loadset('filename',cfg.icaclean_set, ...
    'filepath',cfg.deriv_dir);
dimensionsBeforeInterpolation = size(EEG.data);
labelsBeforeInterpolation = {EEG.chanlocs.labels};
eventsBeforeInterpolation = numel(EEG.event);

% Restore documented global bad scalp channels before the final reference.
% ICA was trained without these channels, but the formal 250-Hz dataset
% retains them so their original locations can be used for interpolation.
if isfield(cfg,'bad_channels') && ~isempty(cfg.bad_channels)
    badChannels = unique(cfg.bad_channels(:)','stable');
    assert(all(badChannels == fix(badChannels)) && ...
        all(ismember(badChannels,cfg.eeg_channels)), ...
        'bad_channels must contain valid EEG-channel indices.');
    assert(isempty(intersect(badChannels, ...
        [cfg.m1_channel cfg.m2_channel cfg.aux_channels])), ...
        ['Mastoid and auxiliary channels cannot use scalp-channel ' ...
        'interpolation.']);
    interpolatedLabels = {EEG.chanlocs(badChannels).labels};
    EEG = pop_interp(EEG,badChannels,'spherical');
    EEG = eeg_checkset(EEG);
    EEG.etc.bad_channel_interpolation = struct( ...
        'channels',badChannels, ...
        'labels',{interpolatedLabels}, ...
        'method','spherical', ...
        'stage','post-ICA pre-reference');
else
    badChannels = [];
    EEG.etc.bad_channel_interpolation = struct( ...
        'channels',[], ...
        'labels',{{}}, ...
        'method','none', ...
        'stage','post-ICA pre-reference');
end
assert(isequal(size(EEG.data),dimensionsBeforeInterpolation), ...
    'Bad-channel interpolation changed data dimensions.');
assert(isequal({EEG.chanlocs.labels},labelsBeforeInterpolation), ...
    'Bad-channel interpolation changed channel labels.');
assert(numel(EEG.event) == eventsBeforeInterpolation, ...
    'Bad-channel interpolation changed the event count.');
assert(all(isfinite(double(EEG.data(badChannels,:))),'all'), ...
    'Interpolated channel data contain nonfinite values.');
assert(isfield(cfg,'reference_mode') && ...
    isfield(cfg,'final_reference_channels') && ...
    isfield(cfg,'reference_tag'), ...
    ['Reference configuration is incomplete. Use the current ' ...
    'config_subject_template.m.']);
validModes = {'average_mastoid','m1','m2'};
assert(ismember(cfg.reference_mode,validModes), ...
    'Unsupported reference_mode: %s',cfg.reference_mode);
assert(strcmpi(EEG.chanlocs(cfg.m1_channel).labels,'M1') && ...
    strcmpi(EEG.chanlocs(cfg.m2_channel).labels,'M2'), ...
    'Configured mastoid indices do not point to M1/M2.');
if strcmp(cfg.reference_mode,'average_mastoid')
    assert(isequal(cfg.final_reference_channels, ...
        [cfg.m1_channel cfg.m2_channel]), ...
        'Average-mastoid mode must use M1 and M2.');
    assert(strcmp(cfg.reference_tag,'mastref'));
else
    assert(strlength(string( ...
        cfg.reference_exception_reason)) > 0, ...
        ['Single-mastoid reference is an exception and requires ' ...
        'reference_exception_reason.']);
    if strcmp(cfg.reference_mode,'m1')
        assert(isequal(cfg.final_reference_channels,cfg.m1_channel));
    else
        assert(isequal(cfg.final_reference_channels,cfg.m2_channel));
    end
end
auxBefore = EEG.data(cfg.aux_channels,:);
EEG = pop_reref(EEG,cfg.final_reference_channels, ...
    'exclude',cfg.aux_channels, ...
    'keepref','on','refica','remove');
EEG.setname = erase(cfg.ref_set,'.set');
referenceResidual = mean(double(EEG.data( ...
    cfg.final_reference_channels,:)),1);
assert(max(abs(referenceResidual),[],'all') < 1e-4, ...
    'Final-reference residual exceeds tolerance.');
assert(max(abs(double(EEG.data( ...
    cfg.aux_channels,:))-double(auxBefore)),[],'all') == 0);
EEG.etc.final_reference = struct( ...
    'policy','average_mastoid_preferred_single_mastoid_exception', ...
    'mode',cfg.reference_mode, ...
    'channels',cfg.final_reference_channels, ...
    'channel_labels',{ ...
        {EEG.chanlocs(cfg.final_reference_channels).labels}}, ...
    'exception_reason',cfg.reference_exception_reason);
EEG = pop_saveset(EEG,'filename', ...
    cfg.ref_set,'filepath',cfg.deriv_dir);

if exist(cfg.eventlist_dir,'dir') ~= 7
    mkdir(cfg.eventlist_dir);
end
rawEL = fullfile(cfg.eventlist_dir,sprintf( ...
    '%s_postica_%s_eventlist_raw.txt', ...
    cfg.subject,cfg.reference_tag));
binnedEL = fullfile(cfg.eventlist_dir,sprintf( ...
    '%s_postica_%s_eventlist_binned.txt', ...
    cfg.subject,cfg.reference_tag));
assert(exist(rawEL,'file') == 0 && ...
    exist(binnedEL,'file') == 0);

EEG = pop_creabasiceventlist(EEG, ...
    'Eventlist',rawEL, ...
    'BoundaryNumeric',{-99}, ...
    'BoundaryString',{'boundary'}, ...
    'AlphanumericCleaning','off', ...
    'Warning','off');
EEG = pop_binlister(EEG, ...
    'BDF',cfg.bdf, ...
    'ExportEL',binnedEL, ...
    'Resetflag','on', ...
    'SendEL2','EEG&Text', ...
    'UpdateEEG','on', ...
    'Warning','off');
EEG = eeg_checkset(EEG,'makeur');
EEG.setname = erase(cfg.binned_set,'.set');

counts = zeros(1,cfg.expected_bins);
for k = 1:numel(EEG.EVENTLIST.eventinfo)
    bins = EEG.EVENTLIST.eventinfo(k).bini;
    if iscell(bins), bins = cell2mat(bins); end
    for b = bins(:)'
        if b >= 1 && b <= cfg.expected_bins
            counts(b) = counts(b)+1;
        end
    end
end
assert(isequal(counts, ...
    repmat(cfg.expected_trials_per_bin, ...
    1,cfg.expected_bins)));
EEG = pop_saveset(EEG,'filename', ...
    cfg.binned_set,'filepath',cfg.deriv_dir);
fprintf('Phase 4 PASS: bins = ');
fprintf('%d ',counts);
fprintf('; interpolated channels = ');
fprintf('%d ',badChannels);
fprintf('; reference = %s; saved %s.\n', ...
    cfg.reference_mode,binnedPath);
