%% Phase 5: epoch, baseline, condition-blind artifact review, final flags.
% First run creates epoch files and stops at the GUI gate.
% After review, set cfg.artifact_review_complete=true and enter bad epochs.

run(fullfile(cfg.repo_root,'scripts','systematic', ...
    'init_n400_runtime.m'));

epochPath = fullfile(cfg.deriv_dir,cfg.epochs_set);
nobasePath = fullfile(cfg.deriv_dir,cfg.nobase_set);
flaggedPath = fullfile(cfg.deriv_dir,cfg.flagged_set);
nobaseFlaggedPath = fullfile( ...
    cfg.deriv_dir,cfg.nobase_flagged_set);
if exist(flaggedPath,'file') == 2 && ...
        exist(nobaseFlaggedPath,'file') == 2
    fprintf(['Phase 5 already complete: final flagged ' ...
        'derivatives are present.\n']);
    return
end

if exist(epochPath,'file') == 0 || ...
        exist(nobasePath,'file') == 0
    EEG = pop_loadset('filename',cfg.binned_set, ...
        'filepath',cfg.deriv_dir);
    PRIMARY = pop_epochbin(EEG, ...
        cfg.epoch_ms,cfg.baseline_ms);
    NOBASE = pop_epochbin(EEG, ...
        cfg.epoch_ms,'none');
    PRIMARY.setname = erase(cfg.epochs_set,'.set');
    NOBASE.setname = erase(cfg.nobase_set,'.set');
    assert(PRIMARY.trials == cfg.expected_trials);
    assert(NOBASE.trials == cfg.expected_trials);
    PRIMARY = pop_saveset(PRIMARY, ...
        'filename',cfg.epochs_set, ...
        'filepath',cfg.deriv_dir);
    NOBASE = pop_saveset(NOBASE, ...
        'filename',cfg.nobase_set, ...
        'filepath',cfg.deriv_dir);
end

if ~cfg.artifact_review_complete
    fprintf(['GUI GATE: review pooled epochs without condition labels, ' ...
        'record bad epochs, then set artifact_review_complete=true ' ...
        'and rerun Phase 5. No trials should be deleted.\n']);
    return
end

assert(exist(flaggedPath,'file') == 0 && ...
    exist(nobaseFlaggedPath,'file') == 0, ...
    'Final Phase 5 output exists; stopped without overwriting.');
PRIMARY = pop_loadset('filename',cfg.epochs_set, ...
    'filepath',cfg.deriv_dir);
NOBASE = pop_loadset('filename',cfg.nobase_set, ...
    'filepath',cfg.deriv_dir);

PRIMARY = localApplyFlags(PRIMARY, ...
    cfg.artifact_bad_epochs, ...
    cfg.m1_channel,cfg.artifact_flag_bit);
NOBASE = localApplyFlags(NOBASE, ...
    cfg.artifact_bad_epochs, ...
    cfg.m1_channel,cfg.artifact_flag_bit);
PRIMARY.setname = erase(cfg.flagged_set,'.set');
NOBASE.setname = erase(cfg.nobase_flagged_set,'.set');

PRIMARY = pop_saveset(PRIMARY, ...
    'filename',cfg.flagged_set, ...
    'filepath',cfg.deriv_dir);
NOBASE = pop_saveset(NOBASE, ...
    'filename',cfg.nobase_flagged_set, ...
    'filepath',cfg.deriv_dir);
fprintf('Phase 5 PASS: %d artifact epochs flagged; no trials deleted.\n', ...
    numel(cfg.artifact_bad_epochs));

function EEG = localApplyFlags(EEG,badEpochs,m1,flagBit)
badEpochs = unique(badEpochs(:)');
assert(all(badEpochs >= 1 & ...
    badEpochs <= EEG.trials));
mask = false(1,EEG.trials);
mask(badEpochs) = true;
EEG.reject.rejmanual = mask;
EEG.reject.rejmanualE = ...
    false(EEG.nbchan,EEG.trials);
EEG.reject.rejmanualE(m1,badEpochs) = true;
for ep = 1:EEG.trials
    eventIndex = EEG.epoch(ep).event;
    eventItem = EEG.epoch(ep).eventitem;
    if iscell(eventIndex), eventIndex = eventIndex{1}; end
    if iscell(eventItem), eventItem = eventItem{1}; end
    assert(isscalar(eventIndex) && ...
        isscalar(eventItem), ...
        'Expected one time-locking event per epoch.');
    flag = bitset(uint16( ...
        EEG.epoch(ep).eventflag), ...
        flagBit,mask(ep));
    EEG.epoch(ep).eventflag = double(flag);
    EEG.event(eventIndex).flag = double(flag);
    EEG.EVENTLIST.eventinfo(eventItem).flag = ...
        double(flag);
end
EEG.etc.artifact_rejection = struct( ...
    'flag_bit',flagBit, ...
    'bad_epochs',badEpochs, ...
    'trials_retained',EEG.trials);
EEG = eeg_checkset(EEG);
end
