%% Phase 3: prepare ICA data, run ICA, transfer weights, remove reviewed ICs.
% Run repeatedly. The script stops at the two required GUI review gates.

run(fullfile(cfg.repo_root,'scripts','systematic', ...
    'init_n400_runtime.m'));

trainingPath = fullfile(cfg.deriv_dir,cfg.icatrain_set);
solutionPath = fullfile(cfg.deriv_dir,cfg.ica_solution_set);
weightsPath = fullfile(cfg.deriv_dir,cfg.icaweights_set);
cleanPath = fullfile(cfg.deriv_dir,cfg.icaclean_set);

%% A. Create the training copy and apply the locked +/-100-uV rule.

if exist(trainingPath,'file') == 0 && ...
        exist(solutionPath,'file') == 0
    EEG = pop_loadset('filename',cfg.preica_set, ...
        'filepath',cfg.deriv_dir);
    EEG = pop_basicfilter(EEG,cfg.ica_channels, ...
        'Filter','highpass','Design','butter', ...
        'Cutoff',cfg.ica_highpass, ...
        'Order',cfg.ica_highpass_order, ...
        'RemoveDC','on','Boundary','boundary');
    EEG = pop_resample(EEG,cfg.ica_rate);

    codes = nan(1,numel(EEG.event));
    for k = 1:numel(EEG.event)
        codes(k) = localEventCode(EEG.event(k).type);
    end
    startCodes = [11:15 21:25];
    startItems = find(ismember(codes,startCodes));
    assert(numel(startItems) == cfg.expected_trials);

    ranges = nan(cfg.expected_trials,2);
    thresholdRejected = false(1,cfg.expected_trials);
    for trial = 1:cfg.expected_trials
        startItem = startItems(trial);
        expectedTarget = codes(startItem)+100;
        targetOffset = find( ...
            codes(startItem+1:end) == expectedTarget,1);
        assert(~isempty(targetOffset), ...
            'Missing target after trial start %d.',trial);
        targetItem = startItem+targetOffset;

        firstPoint = max(1,ceil( ...
            double(EEG.event(startItem).latency)));
        lastPoint = min(EEG.pnts,ceil( ...
            double(EEG.event(targetItem).latency) + ...
            cfg.ica_task_end_seconds*EEG.srate)-1);
        ranges(trial,:) = [firstPoint lastPoint];

        segment = double(EEG.data( ...
            cfg.ica_channels,firstPoint:lastPoint));
        thresholdRejected(trial) = ...
            any(segment(:) < ...
            cfg.ica_simple_threshold_uv(1) | ...
            segment(:) > ...
            cfg.ica_simple_threshold_uv(2));
    end

    keepRanges = ranges(~thresholdRejected,:);
    assert(~isempty(keepRanges), ...
        'The ICA simple threshold rejected every task segment.');
    removeRanges = localComplementRanges( ...
        keepRanges,EEG.pnts);
    if ~isempty(removeRanges)
        EEG = pop_select(EEG,'nopoint',removeRanges);
    end
    EEG.setname = erase(cfg.icatrain_set,'.set');
    EEG.etc.ica_training = struct( ...
        'source',cfg.preica_set, ...
        'highpass_hz',cfg.ica_highpass, ...
        'sampling_rate_hz',cfg.ica_rate, ...
        'retained_window','trial start through target +1 s', ...
        'simple_threshold_uv', ...
        cfg.ica_simple_threshold_uv, ...
        'threshold_unit','complete retained task segment', ...
        'threshold_rejected_trials', ...
        find(thresholdRejected), ...
        'threshold_retained_trials', ...
        find(~thresholdRejected), ...
        'ica_channels',cfg.ica_channels);
    EEG = pop_saveset(EEG,'filename', ...
        cfg.icatrain_set,'filepath',cfg.deriv_dir);

    fprintf(['ICA training copy created. +/-100-uV rule rejected ' ...
        '%d/%d task segments; retained %d samples.\n'], ...
        sum(thresholdRejected),cfg.expected_trials,EEG.pnts);
    fprintf(['GUI GATE: inspect every rejected segment and a sample ' ...
        'of retained segments before setting cfg.run_ica=true.\n']);
    return
end

%% B. Run extended Infomax after the threshold GUI gate.

if exist(solutionPath,'file') == 0
    assert(cfg.run_ica, ...
        ['Set cfg.run_ica=true only after completing the ' ...
        'training-copy GUI review.']);
    EEG = pop_loadset('filename',cfg.icatrain_set, ...
        'filepath',cfg.deriv_dir);
    rng(cfg.ica_random_seed,'twister');
    EEG = pop_runica(EEG, ...
        'icatype','runica', ...
        'extended',1, ...
        'chanind',cfg.ica_channels);
    EEG.setname = erase(cfg.ica_solution_set,'.set');
    EEG = pop_saveset(EEG,'filename', ...
        cfg.ica_solution_set,'filepath',cfg.deriv_dir);
end

%% C. Transfer the locked weights to the complete analysis dataset.

if exist(weightsPath,'file') == 0
    ICA = pop_loadset('filename',cfg.ica_solution_set, ...
        'filepath',cfg.deriv_dir);
    EEG = pop_loadset('filename',cfg.preica_set, ...
        'filepath',cfg.deriv_dir);
    EEG.icaweights = ICA.icaweights;
    EEG.icasphere = ICA.icasphere;
    EEG.icawinv = ICA.icawinv;
    EEG.icachansind = ICA.icachansind;
    EEG.icaact = [];
    EEG = eeg_checkset(EEG);
    EEG.setname = erase(cfg.icaweights_set,'.set');
    EEG = pop_saveset(EEG,'filename', ...
        cfg.icaweights_set,'filepath',cfg.deriv_dir);
end

%% D. Stop for manual IC review, then remove only the entered ICs.

if isempty(cfg.removed_ics)
    fprintf(['GUI GATE: load %s, run ICLabel as decision support, ' ...
        'inspect maps/spectra/time courses/EOG, then enter ' ...
        'cfg.removed_ics and rerun Phase 3.\n'],weightsPath);
    return
end

assert(exist(cleanPath,'file') == 0, ...
    'ICA-clean output exists; stopped without overwriting.');
EEG = pop_loadset('filename',cfg.icaweights_set, ...
    'filepath',cfg.deriv_dir);
assert(all(ismember(cfg.removed_ics, ...
    1:size(EEG.icaweights,1))));
EEG = pop_subcomp(EEG,cfg.removed_ics,0);
EEG.setname = erase(cfg.icaclean_set,'.set');
EEG.etc.ica_rejection = struct( ...
    'removed_components',cfg.removed_ics, ...
    'manual_review_required',true);
EEG = pop_saveset(EEG,'filename', ...
    cfg.icaclean_set,'filepath',cfg.deriv_dir);
fprintf('Phase 3 PASS: ICA-clean derivative saved: %s\n',cleanPath);

function code = localEventCode(value)
if isnumeric(value)
    code = double(value);
else
    token = regexp(char(string(value)), ...
        '-?\d+','match','once');
    code = str2double(token);
end
end

function removeRanges = localComplementRanges(keepRanges,lastPoint)
keepRanges = sortrows(keepRanges,1);
assert(all(keepRanges(:,1) <= keepRanges(:,2)));
assert(all(keepRanges(2:end,1) > ...
    keepRanges(1:end-1,2)));

removeRanges = zeros(0,2);
cursor = 1;
for k = 1:size(keepRanges,1)
    if keepRanges(k,1) > cursor
        removeRanges(end+1,:) = ...
            [cursor keepRanges(k,1)-1]; %#ok<AGROW>
    end
    cursor = keepRanges(k,2)+1;
end
if cursor <= lastPoint
    removeRanges(end+1,:) = ...
        [cursor lastPoint];
end
end
