%% 01A Phase 6: add behavior-exclusion flags in memory
%
% Bit 1 remains the locked M1 reference-quality artifact flag.
% Bit 2 marks behaviorally incorrect trials.
% No trials are deleted and this preview does not save a dataset.

derivPath = ...
    '/Users/kevinchain/Desktop/N400_project/derivatives/';
tablePath = [ ...
    '/Users/kevinchain/Desktop/N400_project/' ...
    'derivatives/tables/01A/'];
primaryFile = ...
    '01A_m1ref_target_epochs_artifactflagged.set';
ledgerFile = fullfile(tablePath, ...
    '01A_m1ref_trial_ledger.csv');

assert(exist(fullfile(derivPath,primaryFile),'file') == 2, ...
    'Final artifact-flagged primary EEG file not found.');
assert(exist(ledgerFile,'file') == 2, ...
    'Phase 6 trial ledger not found.');

if ~exist('PRIMARY_FINAL','var') || ...
        ~isstruct(PRIMARY_FINAL) || ...
        ~isfield(PRIMARY_FINAL,'setname') || ...
        ~strcmp(PRIMARY_FINAL.setname, ...
            '01A_m1ref_target_epochs_artifactflagged')

    PRIMARY_FINAL = pop_loadset( ...
        'filename',primaryFile, ...
        'filepath',derivPath);
    PRIMARY_FINAL = eeg_checkset(PRIMARY_FINAL);
end

LEDGER = readtable(ledgerFile, ...
    'TextType','string');

assert(height(LEDGER) == 300, ...
    'Ledger must contain 300 rows.');
assert(all(LEDGER.BehaviorRow == (1:300)'), ...
    'Ledger behavior-row order is not 1:300.');
assert(all(LEDGER.EEGEpoch == (1:300)'), ...
    'Ledger EEG-epoch order is not 1:300.');
assert(all(LEDGER.TargetCodeMatch), ...
    'Ledger contains a target-code mismatch.');

artifactEpochs = find( ...
    logical(LEDGER.ArtifactFlagBit1))';
incorrectEpochs = find(LEDGER.Correct == 0)';
correctEpochs = find(LEDGER.Correct == 1)';

assert(isequal(artifactEpochs, ...
    [4 22 133 202 206]), ...
    'Ledger artifact list differs from the locked Phase 5 list.');
assert(numel(incorrectEpochs) == 142, ...
    'Expected 142 behaviorally incorrect trials.');
assert(numel(correctEpochs) == 158, ...
    'Expected 158 behaviorally correct trials.');

PRIMARY_CORRECT = PRIMARY_FINAL;
dataBefore = PRIMARY_CORRECT.data;
eventTypesBefore = {PRIMARY_CORRECT.event.type};
eventLatenciesBefore = ...
    double([PRIMARY_CORRECT.event.latency]);
manualBefore = logical( ...
    PRIMARY_CORRECT.reject.rejmanual(:))';
manualEBefore = logical( ...
    PRIMARY_CORRECT.reject.rejmanualE);

assert(isequal(find(manualBefore), ...
    artifactEpochs), ...
    'Source EEG.reject.rejmanual does not match bit 1.');

%% Add a separate behavior-rejection field pair
%
% ERPLAB Averager discovers rejection vectors from paired fields whose
% channel-level field ends in E. Keeping this separate preserves the
% meaning of rejmanual/rejmanualE as the M1 reference-quality detector.

behaviorReject = false(1,PRIMARY_CORRECT.trials);
behaviorReject(incorrectEpochs) = true;

PRIMARY_CORRECT.reject.rejbehavior = ...
    behaviorReject;
PRIMARY_CORRECT.reject.rejbehaviorE = ...
    false(PRIMARY_CORRECT.nbchan, ...
    PRIMARY_CORRECT.trials);

%% Synchronize bit 2 at epoch, EEG.event, and EVENTLIST levels

for ep = 1:PRIMARY_CORRECT.trials
    eventIndex = PRIMARY_CORRECT.epoch(ep).event;
    eventItem = PRIMARY_CORRECT.epoch(ep).eventitem;

    if iscell(eventIndex)
        eventIndex = eventIndex{1};
    end
    if iscell(eventItem)
        eventItem = eventItem{1};
    end

    assert(isscalar(eventIndex) && ...
        isscalar(eventItem), ...
        'Expected one time-locking event per epoch.');

    epochFlag = uint16( ...
        PRIMARY_CORRECT.epoch(ep).eventflag);
    eventFlag = uint16( ...
        PRIMARY_CORRECT.event(eventIndex).flag);
    eventListFlag = uint16( ...
        PRIMARY_CORRECT.EVENTLIST.eventinfo( ...
        eventItem).flag);

    bit2Value = behaviorReject(ep);
    epochFlag = bitset(epochFlag,2,bit2Value);
    eventFlag = bitset(eventFlag,2,bit2Value);
    eventListFlag = bitset( ...
        eventListFlag,2,bit2Value);

    PRIMARY_CORRECT.epoch(ep).eventflag = ...
        double(epochFlag);
    PRIMARY_CORRECT.event(eventIndex).flag = ...
        double(eventFlag);
    PRIMARY_CORRECT.EVENTLIST.eventinfo( ...
        eventItem).flag = ...
        double(eventListFlag);
end

PRIMARY_CORRECT.setname = ...
    '01A_m1ref_target_epochs_correct_behaviorflag_preview';

PRIMARY_CORRECT.etc.behavior_rejection = struct( ...
    'flag_bit',2, ...
    'criterion','Correct == 0', ...
    'source_file',ledgerFile, ...
    'incorrect_epochs',incorrectEpochs, ...
    'correct_epochs',correctEpochs, ...
    'trials_retained',PRIMARY_CORRECT.trials);

historyLine = sprintf([ ...
    '%% Phase 6 behavior flag: bit 2 and ' ...
    'EEG.reject.rejbehavior mark Correct == 0; ' ...
    'all 300 trials retained.']);
if isempty(PRIMARY_CORRECT.history)
    PRIMARY_CORRECT.history = historyLine;
else
    PRIMARY_CORRECT.history = sprintf( ...
        '%s\n%s',PRIMARY_CORRECT.history, ...
        historyLine);
end

PRIMARY_CORRECT = eeg_checkset(PRIMARY_CORRECT);

%% Independent QC extraction

epochFlags = zeros(1,PRIMARY_CORRECT.trials,'uint16');
eventFlags = zeros(1,PRIMARY_CORRECT.trials,'uint16');
eventListFlags = zeros(1,PRIMARY_CORRECT.trials,'uint16');

for ep = 1:PRIMARY_CORRECT.trials
    eventIndex = PRIMARY_CORRECT.epoch(ep).event;
    eventItem = PRIMARY_CORRECT.epoch(ep).eventitem;

    if iscell(eventIndex)
        eventIndex = eventIndex{1};
    end
    if iscell(eventItem)
        eventItem = eventItem{1};
    end

    epochFlags(ep) = uint16( ...
        PRIMARY_CORRECT.epoch(ep).eventflag);
    eventFlags(ep) = uint16( ...
        PRIMARY_CORRECT.event(eventIndex).flag);
    eventListFlags(ep) = uint16( ...
        PRIMARY_CORRECT.EVENTLIST.eventinfo( ...
        eventItem).flag);
end

epochBit1 = bitget(epochFlags,1) == 1;
eventBit1 = bitget(eventFlags,1) == 1;
eventListBit1 = bitget(eventListFlags,1) == 1;
epochBit2 = bitget(epochFlags,2) == 1;
eventBit2 = bitget(eventFlags,2) == 1;
eventListBit2 = bitget(eventListFlags,2) == 1;

assert(isequal(find(epochBit1),artifactEpochs));
assert(isequal(epochBit1,eventBit1));
assert(isequal(epochBit1,eventListBit1));
assert(isequal(find(epochBit2),incorrectEpochs));
assert(isequal(epochBit2,eventBit2));
assert(isequal(epochBit2,eventListBit2));
assert(isequal(logical( ...
    PRIMARY_CORRECT.reject.rejmanual(:))', ...
    manualBefore));
assert(isequal(logical( ...
    PRIMARY_CORRECT.reject.rejmanualE), ...
    manualEBefore));
assert(isequal(find( ...
    PRIMARY_CORRECT.reject.rejbehavior), ...
    incorrectEpochs));
assert(~any( ...
    PRIMARY_CORRECT.reject.rejbehaviorE(:)));
assert(isequal(PRIMARY_CORRECT.data,dataBefore));
assert(isequal({PRIMARY_CORRECT.event.type}, ...
    eventTypesBefore));
assert(isequal(double( ...
    [PRIMARY_CORRECT.event.latency]), ...
    eventLatenciesBefore));

combinedRejected = epochBit1 | epochBit2;
correctAndClean = ~epochBit1 & ~epochBit2;

assert(sum(combinedRejected) == 146);
assert(sum(correctAndClean) == 154);

fprintf('\n=== Phase 6 behavior-flag preview QC ===\n');
fprintf('Trials retained: %d\n', ...
    PRIMARY_CORRECT.trials);
fprintf('Bit 1 artifact epochs: %d\n', ...
    sum(epochBit1));
fprintf('Bit 2 behavior-incorrect epochs: %d\n', ...
    sum(epochBit2));
fprintf('Overlap of bit 1 and bit 2: %d\n', ...
    sum(epochBit1 & epochBit2));
fprintf('Combined rejected / correct-clean: %d / %d\n', ...
    sum(combinedRejected),sum(correctAndClean));
fprintf('Epoch/event/EVENTLIST bit 1 synchronized: %d\n', ...
    isequal(epochBit1,eventBit1,eventListBit1));
fprintf('Epoch/event/EVENTLIST bit 2 synchronized: %d\n', ...
    isequal(epochBit2,eventBit2,eventListBit2));
fprintf('Original rejmanual unchanged: %d\n', ...
    isequal(logical( ...
    PRIMARY_CORRECT.reject.rejmanual(:))', ...
    manualBefore));
fprintf('Original M1 rejmanualE unchanged: %d\n', ...
    isequal(logical( ...
    PRIMARY_CORRECT.reject.rejmanualE), ...
    manualEBefore));
fprintf('Behavior channel marks are all zero: %d\n', ...
    ~any(PRIMARY_CORRECT.reject.rejbehaviorE(:)));
fprintf('Data unchanged: %d\n', ...
    isequal(PRIMARY_CORRECT.data,dataBefore));
fprintf('Event types/latencies unchanged: %d / %d\n', ...
    isequal({PRIMARY_CORRECT.event.type}, ...
    eventTypesBefore), ...
    isequal(double( ...
    [PRIMARY_CORRECT.event.latency]), ...
    eventLatenciesBefore));
fprintf('Preview only; no dataset was saved.\n');
