%% 01A Phase 6: primary and sensitivity ERP averages in memory
%
% Primary: behaviorally correct AND EEG-clean (154 trials).
% Sensitivity: all EEG-clean trials (295 trials).
% This preview does not save ERP files.

erplabPath = [ ...
    '/Users/kevinchain/Documents/MATLAB/' ...
    'eeglab2026.0.0/plugins/erplab-master'];

if exist('pop_averager','file') ~= 2
    assert(exist(erplabPath,'dir') == 7, ...
        'ERPLAB installation was not found.');
    addpath(genpath(erplabPath));
end

assert(exist('pop_averager','file') == 2, ...
    'pop_averager is unavailable after loading ERPLAB.');

if ~exist('PRIMARY_CORRECT','var') || ...
        ~isstruct(PRIMARY_CORRECT) || ...
        ~isfield(PRIMARY_CORRECT,'etc') || ...
        ~isfield(PRIMARY_CORRECT.etc, ...
        'behavior_rejection')

    run([ ...
        '/Users/kevinchain/Documents/Codex/' ...
        'eeg-n400-analysis-skills/scripts/' ...
        'build_01A_phase6_behavior_flags_preview.m']);
end

assert(exist('PRIMARY_FINAL','var') == 1 && ...
    isstruct(PRIMARY_FINAL), ...
    'PRIMARY_FINAL is unavailable.');
assert(PRIMARY_CORRECT.trials == 300 && ...
    PRIMARY_FINAL.trials == 300, ...
    'Expected 300 epochs in both EEG structures.');

%% Build the synchronized primary averaging copy

PRIMARY_AVERAGE_READY = PRIMARY_CORRECT;

epochFlags = zeros(1,300,'uint16');
for ep = 1:300
    epochFlags(ep) = uint16( ...
        PRIMARY_AVERAGE_READY.epoch(ep).eventflag);
end

artifactMask = bitget(epochFlags,1) == 1;
incorrectMask = bitget(epochFlags,2) == 1;
combinedRejectMask = artifactMask | incorrectMask;
primaryGoodMask = ~combinedRejectMask;
sensitivityGoodMask = ~artifactMask;

assert(sum(artifactMask) == 5);
assert(sum(incorrectMask) == 142);
assert(sum(artifactMask & incorrectMask) == 1);
assert(sum(primaryGoodMask) == 154);
assert(sum(sensitivityGoodMask) == 295);

% ERPLAB's synchronization gate treats rejmanual as the total rejection
% mask. Bit 1/bit 2 and the separate rejbehavior field retain the reasons.
PRIMARY_AVERAGE_READY.reject.rejmanual = ...
    combinedRejectMask;
PRIMARY_AVERAGE_READY.setname = ...
    '01A_m1ref_target_epochs_primary_average_ready';
PRIMARY_AVERAGE_READY.etc.behavior_rejection.rejmanual_role = ...
    'union of flag bit 1 artifact and flag bit 2 incorrect';

assert(isequal(logical( ...
    PRIMARY_AVERAGE_READY.reject.rejmanual(:))', ...
    combinedRejectMask));
assert(isequal(find( ...
    PRIMARY_AVERAGE_READY.reject.rejbehavior), ...
    find(incorrectMask)));

%% Extract one bin number per epoch for independent reconstruction

epochBin = nan(1,300);
for ep = 1:300
    binValue = PRIMARY_AVERAGE_READY.epoch(ep).eventbini;
    if iscell(binValue)
        binValue = binValue{1};
    end
    binValue = double(binValue);
    binValue = binValue( ...
        binValue >= 1 & binValue <= 10);
    assert(numel(binValue) == 1, ...
        'Expected one valid bin per epoch.');
    epochBin(ep) = binValue;
end

expectedPrimaryAccepted = ...
    [8 10 21 18 28 4 4 16 23 22];
expectedSensitivityAccepted = ...
    [29 30 30 29 29 29 30 30 30 29];

for b = 1:10
    assert(sum(primaryGoodMask & ...
        epochBin == b) == ...
        expectedPrimaryAccepted(b));
    assert(sum(sensitivityGoodMask & ...
        epochBin == b) == ...
        expectedSensitivityAccepted(b));
end

%% Average with the installed ERPLAB implementation

ERP_PRIMARY_PREVIEW = pop_averager( ...
    PRIMARY_AVERAGE_READY, ...
    'Criterion','good', ...
    'ExcludeBoundary','on', ...
    'SEM','on', ...
    'Warning','off', ...
    'DQ_flag',1);

ERP_PRIMARY_PREVIEW.erpname = ...
    '01A_m1ref_erp_primary_correct_clean_preview';

ERP_SENSITIVITY_PREVIEW = pop_averager( ...
    PRIMARY_FINAL, ...
    'Criterion','good', ...
    'ExcludeBoundary','on', ...
    'SEM','on', ...
    'Warning','off', ...
    'DQ_flag',1);

ERP_SENSITIVITY_PREVIEW.erpname = ...
    '01A_m1ref_erp_sensitivity_all_clean_preview';

%% Structural and count QC

assert(ERP_PRIMARY_PREVIEW.nchan == 67);
assert(ERP_PRIMARY_PREVIEW.pnts == 250);
assert(ERP_PRIMARY_PREVIEW.nbin == 10);
assert(ERP_SENSITIVITY_PREVIEW.nchan == 67);
assert(ERP_SENSITIVITY_PREVIEW.pnts == 250);
assert(ERP_SENSITIVITY_PREVIEW.nbin == 10);

assert(isequal( ...
    ERP_PRIMARY_PREVIEW.ntrials.accepted, ...
    expectedPrimaryAccepted));
assert(isequal( ...
    ERP_SENSITIVITY_PREVIEW.ntrials.accepted, ...
    expectedSensitivityAccepted));
assert(isequal( ...
    ERP_PRIMARY_PREVIEW.ntrials.rejected, ...
    30-expectedPrimaryAccepted));
assert(isequal( ...
    ERP_SENSITIVITY_PREVIEW.ntrials.rejected, ...
    30-expectedSensitivityAccepted));
assert(~any( ...
    ERP_PRIMARY_PREVIEW.ntrials.invalid));
assert(~any( ...
    ERP_SENSITIVITY_PREVIEW.ntrials.invalid));

assert(isequal(ERP_PRIMARY_PREVIEW.times, ...
    PRIMARY_AVERAGE_READY.times));
assert(isequal(ERP_SENSITIVITY_PREVIEW.times, ...
    PRIMARY_FINAL.times));
assert(isequal( ...
    {ERP_PRIMARY_PREVIEW.chanlocs.labels}, ...
    {PRIMARY_AVERAGE_READY.chanlocs.labels}));
assert(isequal( ...
    {ERP_SENSITIVITY_PREVIEW.chanlocs.labels}, ...
    {PRIMARY_FINAL.chanlocs.labels}));
assert(all(isfinite( ...
    ERP_PRIMARY_PREVIEW.bindata(:))));
assert(all(isfinite( ...
    ERP_SENSITIVITY_PREVIEW.bindata(:))));
assert(all(isfinite( ...
    ERP_PRIMARY_PREVIEW.binerror(:))));
assert(all(isfinite( ...
    ERP_SENSITIVITY_PREVIEW.binerror(:))));

%% Independently reconstruct averages and SEM

primaryAverageError = 0;
primarySEMError = 0;
sensitivityAverageError = 0;
sensitivitySEMError = 0;

for b = 1:10
    primaryEpochs = find( ...
        primaryGoodMask & epochBin == b);
    sensitivityEpochs = find( ...
        sensitivityGoodMask & epochBin == b);

    primaryData = double( ...
        PRIMARY_AVERAGE_READY.data( ...
        :,:,primaryEpochs));
    sensitivityData = double( ...
        PRIMARY_FINAL.data( ...
        :,:,sensitivityEpochs));

    reconstructedPrimary = mean( ...
        primaryData,3);
    reconstructedSensitivity = mean( ...
        sensitivityData,3);
    reconstructedPrimarySEM = std( ...
        primaryData,0,3) / ...
        sqrt(numel(primaryEpochs));
    reconstructedSensitivitySEM = std( ...
        sensitivityData,0,3) / ...
        sqrt(numel(sensitivityEpochs));

    erplabPrimary = double( ...
        ERP_PRIMARY_PREVIEW.bindata(:,:,b));
    erplabSensitivity = double( ...
        ERP_SENSITIVITY_PREVIEW.bindata(:,:,b));
    erplabPrimarySEM = double( ...
        ERP_PRIMARY_PREVIEW.binerror(:,:,b));
    erplabSensitivitySEM = double( ...
        ERP_SENSITIVITY_PREVIEW.binerror(:,:,b));

    primaryAverageError = max( ...
        primaryAverageError, ...
        max(abs(reconstructedPrimary(:) - ...
        erplabPrimary(:))));
    sensitivityAverageError = max( ...
        sensitivityAverageError, ...
        max(abs(reconstructedSensitivity(:) - ...
        erplabSensitivity(:))));
    primarySEMError = max( ...
        primarySEMError, ...
        max(abs(reconstructedPrimarySEM(:) - ...
        erplabPrimarySEM(:))));
    sensitivitySEMError = max( ...
        sensitivitySEMError, ...
        max(abs(reconstructedSensitivitySEM(:) - ...
        erplabSensitivitySEM(:))));
end

assert(primaryAverageError < 1e-4);
assert(sensitivityAverageError < 1e-4);
assert(primarySEMError < 1e-4);
assert(sensitivitySEMError < 1e-4);

%% Baseline, reference, and data-quality QC

baselineSamples = ...
    ERP_PRIMARY_PREVIEW.times >= -200 & ...
    ERP_PRIMARY_PREVIEW.times <= 0;
assert(any(baselineSamples));

primaryBaselineMean = mean( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    :,baselineSamples,:),2);
sensitivityBaselineMean = mean( ...
    ERP_SENSITIVITY_PREVIEW.bindata( ...
    :,baselineSamples,:),2);

maxPrimaryBaselineMean = max( ...
    abs(primaryBaselineMean),[],'all');
maxSensitivityBaselineMean = max( ...
    abs(sensitivityBaselineMean),[],'all');

m1Index = find(strcmpi( ...
    {ERP_PRIMARY_PREVIEW.chanlocs.labels}, ...
    'M1'));
assert(isscalar(m1Index));

maxPrimaryM1 = max(abs( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    m1Index,:,:)),[],'all');
maxSensitivityM1 = max(abs( ...
    ERP_SENSITIVITY_PREVIEW.bindata( ...
    m1Index,:,:)),[],'all');
maxPrimaryM1SEM = max(abs( ...
    ERP_PRIMARY_PREVIEW.binerror( ...
    m1Index,:,:)),[],'all');
maxSensitivityM1SEM = max(abs( ...
    ERP_SENSITIVITY_PREVIEW.binerror( ...
    m1Index,:,:)),[],'all');

assert(maxPrimaryBaselineMean < 1e-4);
assert(maxSensitivityBaselineMean < 1e-4);
assert(maxPrimaryM1 == 0);
assert(maxSensitivityM1 == 0);
assert(maxPrimaryM1SEM == 0);
assert(maxSensitivityM1SEM == 0);

assert(isfield( ...
    ERP_PRIMARY_PREVIEW,'dataquality'));
assert(isfield( ...
    ERP_SENSITIVITY_PREVIEW,'dataquality'));

primaryDQTypes = string( ...
    {ERP_PRIMARY_PREVIEW.dataquality.type});
sensitivityDQTypes = string( ...
    {ERP_SENSITIVITY_PREVIEW.dataquality.type});
primaryHasASME = any( ...
    contains(primaryDQTypes,'aSME'));
sensitivityHasASME = any( ...
    contains(sensitivityDQTypes,'aSME'));
assert(primaryHasASME && ...
    sensitivityHasASME);

fprintf('\n=== Phase 6 ERP averaging preview QC ===\n');
fprintf('ERPLAB pop_averager:\n%s\n', ...
    which('pop_averager'));
fprintf('Primary dimensions: %d / %d / %d\n', ...
    ERP_PRIMARY_PREVIEW.nchan, ...
    ERP_PRIMARY_PREVIEW.pnts, ...
    ERP_PRIMARY_PREVIEW.nbin);
fprintf('Sensitivity dimensions: %d / %d / %d\n', ...
    ERP_SENSITIVITY_PREVIEW.nchan, ...
    ERP_SENSITIVITY_PREVIEW.pnts, ...
    ERP_SENSITIVITY_PREVIEW.nbin);
fprintf('Primary accepted per bin: ');
fprintf('%d ', ...
    ERP_PRIMARY_PREVIEW.ntrials.accepted);
fprintf('\n');
fprintf('Sensitivity accepted per bin: ');
fprintf('%d ', ...
    ERP_SENSITIVITY_PREVIEW.ntrials.accepted);
fprintf('\n');
fprintf('Primary total accepted/rejected/invalid: %d / %d / %d\n', ...
    sum(ERP_PRIMARY_PREVIEW.ntrials.accepted), ...
    sum(ERP_PRIMARY_PREVIEW.ntrials.rejected), ...
    sum(ERP_PRIMARY_PREVIEW.ntrials.invalid));
fprintf('Sensitivity total accepted/rejected/invalid: %d / %d / %d\n', ...
    sum(ERP_SENSITIVITY_PREVIEW.ntrials.accepted), ...
    sum(ERP_SENSITIVITY_PREVIEW.ntrials.rejected), ...
    sum(ERP_SENSITIVITY_PREVIEW.ntrials.invalid));
fprintf('Maximum primary/sensitivity average reconstruction error: %.12g / %.12g uV\n', ...
    primaryAverageError, ...
    sensitivityAverageError);
fprintf('Maximum primary/sensitivity SEM reconstruction error: %.12g / %.12g uV\n', ...
    primarySEMError, ...
    sensitivitySEMError);
fprintf('Maximum absolute primary/sensitivity baseline mean: %.12g / %.12g uV\n', ...
    maxPrimaryBaselineMean, ...
    maxSensitivityBaselineMean);
fprintf('Maximum absolute M1, primary/sensitivity: %.12g / %.12g uV\n', ...
    maxPrimaryM1,maxSensitivityM1);
fprintf('Maximum M1 SEM, primary/sensitivity: %.12g / %.12g uV\n', ...
    maxPrimaryM1SEM,maxSensitivityM1SEM);
fprintf('All ERP and SEM values finite: 1\n');
fprintf('aSME structures present: %d / %d\n', ...
    primaryHasASME,sensitivityHasASME);
fprintf('Preview only; no ERP file was saved.\n');
