%% 01A Phase 6: single-participant ERP waveform QC
%
% Morphology inspection only. This script does not choose or score an N400
% window and does not save ERP files.

if ~exist('ERP_PRIMARY_PREVIEW','var') || ...
        ~isstruct(ERP_PRIMARY_PREVIEW) || ...
        ~exist('ERP_SENSITIVITY_PREVIEW','var') || ...
        ~isstruct(ERP_SENSITIVITY_PREVIEW)

    run([ ...
        '/Users/kevinchain/Documents/Codex/' ...
        'eeg-n400-analysis-skills/scripts/' ...
        'build_01A_phase6_erp_average_preview.m']);
end

assert(ERP_PRIMARY_PREVIEW.nbin == 10);
assert(ERP_SENSITIVITY_PREVIEW.nbin == 10);
assert(isequal(ERP_PRIMARY_PREVIEW.times, ...
    ERP_SENSITIVITY_PREVIEW.times));
assert(isequal( ...
    {ERP_PRIMARY_PREVIEW.chanlocs.labels}, ...
    {ERP_SENSITIVITY_PREVIEW.chanlocs.labels}));

channelLabels = upper(string( ...
    {ERP_PRIMARY_PREVIEW.chanlocs.labels}));

roiLabels = [ ...
    "C5","C3","C1","CZ","C2","C4","C6", ...
    "CP5","CP3","CP1","CPZ","CP2","CP4","CP6"];

[roiFound,roiIndices] = ismember( ...
    roiLabels,channelLabels);
assert(all(roiFound), ...
    'One or more prespecified ROI channels are missing.');

cpzIndex = find(channelLabels == "CPZ");
assert(isscalar(cpzIndex), ...
    'CPZ was not found uniquely.');

times = ERP_PRIMARY_PREVIEW.times(:);

primaryCPZ = squeeze(double( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    cpzIndex,:,:)));
sensitivityCPZ = squeeze(double( ...
    ERP_SENSITIVITY_PREVIEW.bindata( ...
    cpzIndex,:,:)));
primaryROI = squeeze(mean(double( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    roiIndices,:,:)),1));
sensitivityROI = squeeze(mean(double( ...
    ERP_SENSITIVITY_PREVIEW.bindata( ...
    roiIndices,:,:)),1));

assert(isequal(size(primaryCPZ),[250 10]));
assert(isequal(size(sensitivityCPZ),[250 10]));
assert(isequal(size(primaryROI),[250 10]));
assert(isequal(size(sensitivityROI),[250 10]));

allDisplayedValues = [ ...
    primaryCPZ(:);sensitivityCPZ(:); ...
    primaryROI(:);sensitivityROI(:)];
plotLimit = max(5, ...
    5*ceil(max(abs(allDisplayedValues))/5));

primarySensitivityRMSCPZ = sqrt(mean( ...
    (primaryCPZ-sensitivityCPZ).^2,'all'));
primarySensitivityRMSROI = sqrt(mean( ...
    (primaryROI-sensitivityROI).^2,'all'));

snrNames = ["-4 dB","-2 dB","+4 dB","+6 dB","quiet"];
colorHCPrimary = [0.00 0.25 0.75];
colorLCPrimary = [0.80 0.10 0.10];
colorHCSensitivity = [0.35 0.65 1.00];
colorLCSensitivity = [1.00 0.55 0.25];

figure( ...
    'Name','01A Phase 6 ERP morphology QC', ...
    'Color','w', ...
    'Position',[80 80 1500 760]);

layout = tiledlayout(2,5, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for snrIndex = 1:5
    hcBin = snrIndex;
    lcBin = snrIndex+5;

    nexttile(snrIndex);
    hold on;
    plot(times,primaryCPZ(:,hcBin), ...
        'Color',colorHCPrimary, ...
        'LineWidth',1.5);
    plot(times,primaryCPZ(:,lcBin), ...
        'Color',colorLCPrimary, ...
        'LineWidth',1.5);
    plot(times,sensitivityCPZ(:,hcBin), ...
        '--','Color',colorHCSensitivity, ...
        'LineWidth',1.1);
    plot(times,sensitivityCPZ(:,lcBin), ...
        '--','Color',colorLCSensitivity, ...
        'LineWidth',1.1);
    xline(0,'k:');
    yline(0,'k:');
    xlim([-200 796]);
    ylim([-plotLimit plotLimit]);
    set(gca,'YDir','reverse');
    grid on;
    title(snrNames(snrIndex));
    if snrIndex == 1
        ylabel('CPZ amplitude (\muV)');
        legend( ...
            {'HC primary','LC primary', ...
            'HC all-clean','LC all-clean'}, ...
            'Location','best', ...
            'FontSize',8);
    end
end

for snrIndex = 1:5
    hcBin = snrIndex;
    lcBin = snrIndex+5;

    nexttile(5+snrIndex);
    hold on;
    plot(times,primaryROI(:,hcBin), ...
        'Color',colorHCPrimary, ...
        'LineWidth',1.5);
    plot(times,primaryROI(:,lcBin), ...
        'Color',colorLCPrimary, ...
        'LineWidth',1.5);
    plot(times,sensitivityROI(:,hcBin), ...
        '--','Color',colorHCSensitivity, ...
        'LineWidth',1.1);
    plot(times,sensitivityROI(:,lcBin), ...
        '--','Color',colorLCSensitivity, ...
        'LineWidth',1.1);
    xline(0,'k:');
    yline(0,'k:');
    xlim([-200 796]);
    ylim([-plotLimit plotLimit]);
    set(gca,'YDir','reverse');
    grid on;
    xlabel('Time from target onset (ms)');
    if snrIndex == 1
        ylabel('14-channel ROI amplitude (\muV)');
    end
end

title(layout,[ ...
    '01A target-locked ERP morphology: ' ...
    'primary solid, all-clean dashed; negative up']);

fprintf('\n=== Phase 6 ERP waveform-plot QC ===\n');
fprintf('Prespecified ROI channels found: %d/%d\n', ...
    sum(roiFound),numel(roiLabels));
fprintf('CPZ index: %d\n',cpzIndex);
fprintf('Plot range: %.1f to %.1f uV; negative plotted upward\n', ...
    -plotLimit,plotLimit);
fprintf('Primary-vs-sensitivity RMS difference, CPZ: %.6f uV\n', ...
    primarySensitivityRMSCPZ);
fprintf('Primary-vs-sensitivity RMS difference, ROI: %.6f uV\n', ...
    primarySensitivityRMSROI);
fprintf('Displayed values finite: %d\n', ...
    all(isfinite(allDisplayedValues)));
fprintf('N400 score window applied: 0\n');
fprintf('ERP files saved by this script: 0\n');
