%% 01A Phase 6: primary-only CZ and midline ROI difference-wave plot
%
% HC is blue, LC is red, and the black difference wave is HC minus LC.
% Negative voltage is plotted upward. No score window is applied.
% The earlier morphology-QC figure and all ERP structures are unchanged.

if ~exist('ERP_PRIMARY_PREVIEW','var') || ...
        ~isstruct(ERP_PRIMARY_PREVIEW)

    run([ ...
        '/Users/kevinchain/Documents/Codex/' ...
        'eeg-n400-analysis-skills/scripts/' ...
        'build_01A_phase6_erp_average_preview.m']);
end

assert(ERP_PRIMARY_PREVIEW.nbin == 10);
assert(ERP_PRIMARY_PREVIEW.nchan == 67);
assert(ERP_PRIMARY_PREVIEW.pnts == 250);

channelLabels = upper(string( ...
    {ERP_PRIMARY_PREVIEW.chanlocs.labels}));

roiLabels = ["FZ","FCZ","CZ","CPZ"];
[roiFound,roiIndices] = ismember( ...
    roiLabels,channelLabels);
assert(all(roiFound), ...
    'One or more requested ROI channels are missing.');

czIndex = find(channelLabels == "CZ");
assert(isscalar(czIndex), ...
    'CZ was not found uniquely.');

times = ERP_PRIMARY_PREVIEW.times(:);
primaryCZ = squeeze(double( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    czIndex,:,:)));
primaryROI = squeeze(mean(double( ...
    ERP_PRIMARY_PREVIEW.bindata( ...
    roiIndices,:,:)),1));

assert(isequal(size(primaryCZ),[250 10]));
assert(isequal(size(primaryROI),[250 10]));

czDifference = zeros(250,5);
roiDifference = zeros(250,5);

for snrIndex = 1:5
    hcBin = snrIndex;
    lcBin = snrIndex+5;
    czDifference(:,snrIndex) = ...
        primaryCZ(:,hcBin) - ...
        primaryCZ(:,lcBin);
    roiDifference(:,snrIndex) = ...
        primaryROI(:,hcBin) - ...
        primaryROI(:,lcBin);
end

allDisplayedValues = [ ...
    primaryCZ(:);primaryROI(:); ...
    czDifference(:);roiDifference(:)];
plotLimit = max(5, ...
    5*ceil(max(abs(allDisplayedValues))/5));

snrNames = ["-4 dB","-2 dB","+4 dB","+6 dB","quiet"];
colorHC = [0.00 0.25 0.75];
colorLC = [0.82 0.08 0.08];
colorDifference = [0.00 0.00 0.00];
accepted = ERP_PRIMARY_PREVIEW.ntrials.accepted;

figure( ...
    'Name','01A primary ERP: CZ and FZ-FCZ-CZ-CPZ ROI', ...
    'Color','w', ...
    'Position',[80 80 1500 760]);

layout = tiledlayout(2,5, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for snrIndex = 1:5
    hcBin = snrIndex;
    lcBin = snrIndex+5;

    nexttile(snrIndex);
    hold on;
    plot(times,primaryCZ(:,hcBin), ...
        'Color',colorHC, ...
        'LineWidth',1.5);
    plot(times,primaryCZ(:,lcBin), ...
        'Color',colorLC, ...
        'LineWidth',1.5);
    plot(times,czDifference(:,snrIndex), ...
        'Color',colorDifference, ...
        'LineWidth',2.0);
    xline(0,'k:');
    yline(0,'Color',[0.4 0.4 0.4], ...
        'LineStyle',':');
    xlim([-200 796]);
    ylim([-plotLimit plotLimit]);
    set(gca,'YDir','reverse');
    grid on;
    title(sprintf( ...
        '%s; HC n=%d, LC n=%d', ...
        snrNames(snrIndex), ...
        accepted(hcBin),accepted(lcBin)));
    if snrIndex == 1
        ylabel('CZ amplitude (\muV)');
        legend( ...
            {'HC primary','LC primary', ...
            'HC - LC'}, ...
            'Location','best', ...
            'FontSize',8);
    end
end

for snrIndex = 1:5
    hcBin = snrIndex;
    lcBin = snrIndex+5;

    nexttile(5+snrIndex);
    hold on;
    plot(times,primaryROI(:,hcBin), ...
        'Color',colorHC, ...
        'LineWidth',1.5);
    plot(times,primaryROI(:,lcBin), ...
        'Color',colorLC, ...
        'LineWidth',1.5);
    plot(times,roiDifference(:,snrIndex), ...
        'Color',colorDifference, ...
        'LineWidth',2.0);
    xline(0,'k:');
    yline(0,'Color',[0.4 0.4 0.4], ...
        'LineStyle',':');
    xlim([-200 796]);
    ylim([-plotLimit plotLimit]);
    set(gca,'YDir','reverse');
    grid on;
    xlabel('Time from target onset (ms)');
    if snrIndex == 1
        ylabel('FZ/FCZ/CZ/CPZ ROI (\muV)');
    end
end

title(layout,[ ...
    '01A primary correct-clean ERP: HC blue, LC red, ' ...
    'HC - LC black; negative up']);

fprintf('\n=== Primary CZ/midline-ROI difference plot QC ===\n');
fprintf('Requested ROI channels found: %d/%d\n', ...
    sum(roiFound),numel(roiLabels));
fprintf('ROI labels: %s\n', ...
    strjoin(roiLabels,', '));
fprintf('CZ index: %d\n',czIndex);
fprintf('Difference formula: HC - LC\n');
fprintf('Primary accepted HC bins: ');
fprintf('%d ',accepted(1:5));
fprintf('\n');
fprintf('Primary accepted LC bins: ');
fprintf('%d ',accepted(6:10));
fprintf('\n');
fprintf('Plot range: %.1f to %.1f uV; negative plotted upward\n', ...
    -plotLimit,plotLimit);
fprintf('Displayed values finite: %d\n', ...
    all(isfinite(allDisplayedValues)));
fprintf('N400 score window applied: 0\n');
fprintf('Earlier figure modified: 0\n');
fprintf('ERP files saved by this script: 0\n');
