%% 01A Phase 6: save final ERPsets and reload QC

erpPath = [ ...
    '/Users/kevinchain/Desktop/N400_project/' ...
    'derivatives/erp/01A/'];
primaryERPFile = ...
    '01A_m1ref_erp_primary_correct_clean.erp';
sensitivityERPFile = ...
    '01A_m1ref_erp_sensitivity_all_clean.erp';

if ~exist('ERP_PRIMARY_PREVIEW','var') || ...
        ~isstruct(ERP_PRIMARY_PREVIEW) || ...
        ~exist('ERP_SENSITIVITY_PREVIEW','var') || ...
        ~isstruct(ERP_SENSITIVITY_PREVIEW)

    run([ ...
        '/Users/kevinchain/Documents/Codex/' ...
        'eeg-n400-analysis-skills/scripts/' ...
        'build_01A_phase6_erp_average_preview.m']);
end

assert(exist('pop_savemyerp','file') == 2);
assert(exist('pop_loaderp','file') == 2);
assert(exist(fullfile( ...
    erpPath,primaryERPFile),'file') == 0, ...
    'Primary ERP file already exists; stopped without overwriting.');
assert(exist(fullfile( ...
    erpPath,sensitivityERPFile),'file') == 0, ...
    'Sensitivity ERP file already exists; stopped without overwriting.');

ERP_PRIMARY_FINAL = ERP_PRIMARY_PREVIEW;
ERP_SENSITIVITY_FINAL = ERP_SENSITIVITY_PREVIEW;

ERP_PRIMARY_FINAL.erpname = ...
    '01A_m1ref_erp_primary_correct_clean';
ERP_PRIMARY_FINAL.subject = '01A';
ERP_SENSITIVITY_FINAL.erpname = ...
    '01A_m1ref_erp_sensitivity_all_clean';
ERP_SENSITIVITY_FINAL.subject = '01A';

primaryHistoryLine = [ ...
    '% Final Phase 6 ERP: primary average includes only ' ...
    'behaviorally correct and EEG-clean epochs; ' ...
    'HC-LC-SNR bins retained separately.'];
sensitivityHistoryLine = [ ...
    '% Final Phase 6 ERP sensitivity: average includes all ' ...
    'EEG-clean epochs regardless of behavior correctness; ' ...
    'HC-LC-SNR bins retained separately.'];

if isempty(ERP_PRIMARY_FINAL.history)
    ERP_PRIMARY_FINAL.history = primaryHistoryLine;
else
    ERP_PRIMARY_FINAL.history = sprintf( ...
        '%s\n%s',ERP_PRIMARY_FINAL.history, ...
        primaryHistoryLine);
end
if isempty(ERP_SENSITIVITY_FINAL.history)
    ERP_SENSITIVITY_FINAL.history = ...
        sensitivityHistoryLine;
else
    ERP_SENSITIVITY_FINAL.history = sprintf( ...
        '%s\n%s',ERP_SENSITIVITY_FINAL.history, ...
        sensitivityHistoryLine);
end

primaryBindataBefore = ...
    ERP_PRIMARY_FINAL.bindata;
primaryBinerrorBefore = ...
    ERP_PRIMARY_FINAL.binerror;
sensitivityBindataBefore = ...
    ERP_SENSITIVITY_FINAL.bindata;
sensitivityBinerrorBefore = ...
    ERP_SENSITIVITY_FINAL.binerror;

[ERP_PRIMARY_FINAL,primarySaveStatus] = ...
    pop_savemyerp(ERP_PRIMARY_FINAL, ...
    'erpname',ERP_PRIMARY_FINAL.erpname, ...
    'filename',primaryERPFile, ...
    'filepath',erpPath, ...
    'gui','none', ...
    'Warning','off', ...
    'History','script');

[ERP_SENSITIVITY_FINAL,sensitivitySaveStatus] = ...
    pop_savemyerp(ERP_SENSITIVITY_FINAL, ...
    'erpname',ERP_SENSITIVITY_FINAL.erpname, ...
    'filename',sensitivityERPFile, ...
    'filepath',erpPath, ...
    'gui','none', ...
    'Warning','off', ...
    'History','script');

assert(primarySaveStatus == 2);
assert(sensitivitySaveStatus == 2);
assert(exist(fullfile( ...
    erpPath,primaryERPFile),'file') == 2);
assert(exist(fullfile( ...
    erpPath,sensitivityERPFile),'file') == 2);

ERP_PRIMARY_RELOADED = pop_loaderp( ...
    'filename',primaryERPFile, ...
    'filepath',erpPath, ...
    'overwrite','off', ...
    'Warning','off', ...
    'UpdateMainGui','off', ...
    'History','off');

ERP_SENSITIVITY_RELOADED = pop_loaderp( ...
    'filename',sensitivityERPFile, ...
    'filepath',erpPath, ...
    'overwrite','off', ...
    'Warning','off', ...
    'UpdateMainGui','off', ...
    'History','off');

primaryDataDifference = max(abs( ...
    double(ERP_PRIMARY_RELOADED.bindata(:)) - ...
    double(primaryBindataBefore(:))));
primarySEM_difference = max(abs( ...
    double(ERP_PRIMARY_RELOADED.binerror(:)) - ...
    double(primaryBinerrorBefore(:))));
sensitivityDataDifference = max(abs( ...
    double(ERP_SENSITIVITY_RELOADED.bindata(:)) - ...
    double(sensitivityBindataBefore(:))));
sensitivitySEM_difference = max(abs( ...
    double(ERP_SENSITIVITY_RELOADED.binerror(:)) - ...
    double(sensitivityBinerrorBefore(:))));

assert(primaryDataDifference == 0);
assert(primarySEM_difference == 0);
assert(sensitivityDataDifference == 0);
assert(sensitivitySEM_difference == 0);
assert(isequal(ERP_PRIMARY_RELOADED.times, ...
    ERP_PRIMARY_FINAL.times));
assert(isequal(ERP_SENSITIVITY_RELOADED.times, ...
    ERP_SENSITIVITY_FINAL.times));
assert(isequal( ...
    {ERP_PRIMARY_RELOADED.chanlocs.labels}, ...
    {ERP_PRIMARY_FINAL.chanlocs.labels}));
assert(isequal( ...
    {ERP_SENSITIVITY_RELOADED.chanlocs.labels}, ...
    {ERP_SENSITIVITY_FINAL.chanlocs.labels}));
assert(isequaln(ERP_PRIMARY_RELOADED.ntrials, ...
    ERP_PRIMARY_FINAL.ntrials));
assert(isequaln(ERP_SENSITIVITY_RELOADED.ntrials, ...
    ERP_SENSITIVITY_FINAL.ntrials));
assert(isequaln( ...
    ERP_PRIMARY_RELOADED.dataquality, ...
    ERP_PRIMARY_FINAL.dataquality));
assert(isequaln( ...
    ERP_SENSITIVITY_RELOADED.dataquality, ...
    ERP_SENSITIVITY_FINAL.dataquality));
assert(isequal( ...
    ERP_PRIMARY_RELOADED.bindescr, ...
    ERP_PRIMARY_FINAL.bindescr));
assert(isequal( ...
    ERP_SENSITIVITY_RELOADED.bindescr, ...
    ERP_SENSITIVITY_FINAL.bindescr));
assert(isequaln( ...
    ERP_PRIMARY_RELOADED.EVENTLIST, ...
    ERP_PRIMARY_FINAL.EVENTLIST));
assert(isequaln( ...
    ERP_SENSITIVITY_RELOADED.EVENTLIST, ...
    ERP_SENSITIVITY_FINAL.EVENTLIST));
assert(contains( ...
    ERP_PRIMARY_RELOADED.history, ...
    'behaviorally correct and EEG-clean'));
assert(contains( ...
    ERP_SENSITIVITY_RELOADED.history, ...
    'all EEG-clean epochs'));

primaryInfo = dir(fullfile( ...
    erpPath,primaryERPFile));
sensitivityInfo = dir(fullfile( ...
    erpPath,sensitivityERPFile));

fprintf('\n=== Final ERP save/reload QC ===\n');
fprintf('Primary dimensions: %d / %d / %d\n', ...
    ERP_PRIMARY_RELOADED.nchan, ...
    ERP_PRIMARY_RELOADED.pnts, ...
    ERP_PRIMARY_RELOADED.nbin);
fprintf('Sensitivity dimensions: %d / %d / %d\n', ...
    ERP_SENSITIVITY_RELOADED.nchan, ...
    ERP_SENSITIVITY_RELOADED.pnts, ...
    ERP_SENSITIVITY_RELOADED.nbin);
fprintf('Primary accepted per bin: ');
fprintf('%d ', ...
    ERP_PRIMARY_RELOADED.ntrials.accepted);
fprintf('\n');
fprintf('Sensitivity accepted per bin: ');
fprintf('%d ', ...
    ERP_SENSITIVITY_RELOADED.ntrials.accepted);
fprintf('\n');
fprintf('Bindata difference, primary/sensitivity: %.12g / %.12g uV\n', ...
    primaryDataDifference, ...
    sensitivityDataDifference);
fprintf('SEM difference, primary/sensitivity: %.12g / %.12g uV\n', ...
    primarySEM_difference, ...
    sensitivitySEM_difference);
fprintf('Times and labels retained: %d / %d\n', ...
    isequal(ERP_PRIMARY_RELOADED.times, ...
    ERP_PRIMARY_FINAL.times) && ...
    isequal(ERP_SENSITIVITY_RELOADED.times, ...
    ERP_SENSITIVITY_FINAL.times), ...
    isequal( ...
    {ERP_PRIMARY_RELOADED.chanlocs.labels}, ...
    {ERP_PRIMARY_FINAL.chanlocs.labels}) && ...
    isequal( ...
    {ERP_SENSITIVITY_RELOADED.chanlocs.labels}, ...
    {ERP_SENSITIVITY_FINAL.chanlocs.labels}));
fprintf('Trial counts retained exactly: %d / %d\n', ...
    isequaln(ERP_PRIMARY_RELOADED.ntrials, ...
    ERP_PRIMARY_FINAL.ntrials), ...
    isequaln(ERP_SENSITIVITY_RELOADED.ntrials, ...
    ERP_SENSITIVITY_FINAL.ntrials));
fprintf('Data-quality structures retained exactly: %d / %d\n', ...
    isequaln( ...
    ERP_PRIMARY_RELOADED.dataquality, ...
    ERP_PRIMARY_FINAL.dataquality), ...
    isequaln( ...
    ERP_SENSITIVITY_RELOADED.dataquality, ...
    ERP_SENSITIVITY_FINAL.dataquality));
fprintf('EVENTLIST retained exactly: %d / %d\n', ...
    isequaln( ...
    ERP_PRIMARY_RELOADED.EVENTLIST, ...
    ERP_PRIMARY_FINAL.EVENTLIST), ...
    isequaln( ...
    ERP_SENSITIVITY_RELOADED.EVENTLIST, ...
    ERP_SENSITIVITY_FINAL.EVENTLIST));
fprintf('History documents inclusion rule: %d / %d\n', ...
    contains(ERP_PRIMARY_RELOADED.history, ...
    'behaviorally correct and EEG-clean'), ...
    contains(ERP_SENSITIVITY_RELOADED.history, ...
    'all EEG-clean epochs'));
fprintf('ERP files present: %d / %d\n', ...
    exist(fullfile( ...
    erpPath,primaryERPFile),'file') == 2, ...
    exist(fullfile( ...
    erpPath,sensitivityERPFile),'file') == 2);
fprintf('ERP file bytes, primary/sensitivity: %d / %d\n', ...
    primaryInfo.bytes,sensitivityInfo.bytes);
fprintf('Primary ERP:\n%s\n', ...
    fullfile(erpPath,primaryERPFile));
fprintf('Sensitivity ERP:\n%s\n', ...
    fullfile(erpPath,sensitivityERPFile));
