%% 828update Phase 3: locked 0.1-30 Hz, 250 Hz formal filtering.

run(fullfile(fileparts(mfilename('fullpath')),'init_828_runtime.m'));
outputPath = fullfile(cfg.continuous_dir,cfg.preica_set);
qcPath = fullfile(cfg.qc_dir,sprintf( ...
    '%s_828update_%s_phase03_filter_qc.csv', ...
    cfg.subject,cfg.reference_tag));
logPath = fullfile(cfg.logs_dir,sprintf( ...
    '%s_828update_%s_phase03_pass.txt',cfg.subject,cfg.reference_tag));
present = [exist(outputPath,'file') == 2,exist(qcPath,'file') == 2, ...
    exist(logPath,'file') == 2];
if all(present)
    fprintf('828update Phase 3 already complete: %s\n',outputPath);
    return
end
assert(~any(present),'Partial Phase 3 output exists; inspect before rerunning.');

EEG = pop_loadset('filename',cfg.referenced_set, ...
    'filepath',cfg.continuous_dir);
EEG = eeg_checkset(EEG);
eventCodesBefore = arrayfun(@(x) n400u_event_code(x.type),EEG.event);
targetCountBefore = sum(ismember(eventCodesBefore,[111:115 121:125]));
labelsBefore = {EEG.chanlocs.labels};
inputRate = EEG.srate;
preSD = std(double(EEG.data),0,2);
preRange = max(double(EEG.data),[],2)-min(double(EEG.data),[],2);

EEG = pop_resample(EEG,cfg.analysis_rate);
triggerAfterResample = EEG.data(cfg.trigger_channel,:);
eventLatenciesAfterResample = double([EEG.event.latency]);
EEG = pop_basicfilter(EEG,[cfg.eeg_channels cfg.eog_channels], ...
    'Filter','highpass','Design','butter', ...
    'Cutoff',cfg.analysis_highpass,'Order',cfg.analysis_highpass_order, ...
    'RemoveDC','on','Boundary','boundary');
EEG = pop_basicfilter(EEG,[cfg.eeg_channels cfg.eog_channels], ...
    'Filter','lowpass','Design','butter', ...
    'Cutoff',cfg.analysis_lowpass,'Order',cfg.analysis_lowpass_order, ...
    'RemoveDC','on','Boundary','boundary');
EEG = eeg_checkset(EEG);
assert(max(abs(double(EEG.data(cfg.trigger_channel,:))- ...
    double(triggerAfterResample)),[],'all') == 0, ...
    'TRIGGER changed during filtering.');
assert(isequal(double([EEG.event.latency]),eventLatenciesAfterResample));
assert(isequal({EEG.chanlocs.labels},labelsBefore));
assert(all(isfinite(double(EEG.data(:)))));
eventCodesAfter = arrayfun(@(x) n400u_event_code(x.type),EEG.event);
assert(sum(ismember(eventCodesAfter,[111:115 121:125])) == ...
    targetCountBefore && targetCountBefore == cfg.expected_trials);
if strcmp(cfg.reference_mode,'average_mastoid')
    residual = mean(double(EEG.data([cfg.m1_channel cfg.m2_channel],:)),1);
elseif strcmp(cfg.reference_mode,'m1')
    residual = double(EEG.data(cfg.m1_channel,:));
else
    residual = double(EEG.data(cfg.m2_channel,:));
end
assert(max(abs(residual),[],'all') < 1e-3, ...
    'Reference residual changed unexpectedly during filtering.');

postSD = std(double(EEG.data),0,2);
postRange = max(double(EEG.data),[],2)-min(double(EEG.data),[],2);
FILTER_QC = table((1:EEG.nbchan)',string({EEG.chanlocs.labels})', ...
    preSD,preRange,postSD,postRange, ...
    'VariableNames',{'Channel','Label','PreFilterSD_uV', ...
    'PreFilterRange_uV','PostFilterSD_uV','PostFilterRange_uV'});
writetable(FILTER_QC,qcPath);
EEG.setname = erase(cfg.preica_set,'.set');
EEG.etc.update828_filter = struct('source',cfg.referenced_set, ...
    'input_rate_hz',inputRate,'output_rate_hz',cfg.analysis_rate, ...
    'highpass_hz',cfg.analysis_highpass, ...
    'highpass_effective_order',cfg.analysis_highpass_order, ...
    'lowpass_hz',cfg.analysis_lowpass, ...
    'lowpass_effective_order',cfg.analysis_lowpass_order, ...
    'trigger_filtered',false);
n400u_assert_dataset_absent(outputPath);
EEG = pop_saveset(EEG,'filename',cfg.preica_set, ...
    'filepath',cfg.continuous_dir);
CHECK = pop_loadset('filename',cfg.preica_set,'filepath',cfg.continuous_dir);
assert(isequaln(CHECK.data,EEG.data));
n400u_write_stage_log(cfg,'phase03',{ ...
    sprintf('Input: %s',cfg.referenced_set), ...
    sprintf('Input rate: %g Hz',inputRate), ...
    sprintf('Output rate: %g Hz',cfg.analysis_rate), ...
    sprintf('Filter: %g-%g Hz Butterworth', ...
        cfg.analysis_highpass,cfg.analysis_lowpass), ...
    sprintf('TRIGGER filtered: 0'), ...
    sprintf('Target events: %d',targetCountBefore), ...
    sprintf('Output: %s',outputPath)});
fprintf('828update Phase 3 PASS: %g-%g Hz at %g Hz; saved %s.\n', ...
    cfg.analysis_highpass,cfg.analysis_lowpass,cfg.analysis_rate,outputPath);
